### ISSUE TITLE
url_helper.py[WARNING]: Exception(s) [UrlError('Failed to parse

### ISSUE THREAD

**Issue by brunoaduarte** [canonical/cloud-init#4316] opened 2023-08-04 10:43 UTC
How can I fix this error?

It happens everytime I restart my Ubuntu AWS virtual machine.

```
[   13.512947] cloud-init[477]: Cloud-init v. 23.2.1-0ubuntu0~20.04.2 running 'init-local' at Fri, 04 Aug 2023 09:56:19 +0000. Up 13.23 seconds.
[   13.515664] cloud-init[477]: 2023-08-04 09:56:20,232 - url_helper.py[WARNING]: Exception(s) [UrlError('Failed to parse: http://169.254.169.254/latest/api/token'), UrlError('Failed to parse: http://[fd00:ec2::254]/latest/api/token')] during request to http://[fd00:ec2::254]/latest/api/token, raising last exception
```

**Comment by blackboxsw** [comment] 2023-08-04 20:35
Thanks @brunoaduarte for filing this bug  and making cloud-init better. I don't think we quite have enough information here to give us an idea of the failure path and fix. In IRC you mentioned this is an upgrade path for a long lived instance. Please attach cloud-init.logs (obtained with `sudo cloud-init collect-logs`) you may want to double check your /var/log/cloud-init.log to ensure any sensitive passwords are REDACTED in that log).


Also can you attach the output of you network config:
 ip r
 ip -6 r
 ip addr

**Comment by blackboxsw** [comment] 2023-08-04 20:38
Testing locally, cloud-init uses, urllib.urlparse on any URLs prior to attempting to read them, and this error doesn't make sense on it's own because python's urlparse on Ubuntu Jammy seems to like that just fine
```
 python3 -c 'from urllib.parse import quote, urlparse, urlunparse; print(urlparse("http://[fd00:ec2::254]/latest/api/token"))'
ParseResult(scheme='http', netloc='[fd00:ec2::254]', path='/latest/api/token', params='', query='', fragment='')
```
Something else seems to be mangling that URL before urlparse verifies it.

**Comment by blackboxsw** [comment] 2023-08-04 20:40
Please also explain:
 -  the environment in which you are running, instance type and network config ipv4, ipv4/6 or ipv6-only
 - symptoms you are seeing as a result of this error, as typically I'd expect the url_helper.dual_stack implementation to retry on the ipv4 routes and get the IPv4

**Comment by brunoaduarte** [comment] 2023-08-04 20:48
Sure, here's the logs

**Comment by brunoaduarte** [comment] 2023-08-09 14:53
@blackboxsw 

1. Python 3.8.10
2. not able to run the cmd
```
python3 -c 'from urllib.parse urlparse; print(urlparse("http://169.254.169.254/latest/api/token"))'
  File "<string>", line 1
    from urllib.parse urlparse; print(urlparse("http://169.254.169.254/latest/api/token"))
                      ^
SyntaxError: invalid syntax
```
also
```
Python 3.8.10 (default, May 26 2023, 14:05:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib
>>> print(urllib.parse("http://169.254.169.254/latest/api/token"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'urllib' has no attribute 'parse'
```
also
```
Python 3.8.10 (default, May 26 2023, 14:05:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib.parse
>>> print(urllib.parse("http://169.254.169.254/latest/api/token"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
```
3.
```
curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 120"
AQAEAAc0ZuobTBpi_mnbB5kDnAOCmVONR2wey_6YvM3BhNPCun60LA==
```

4. Here are all the pip installed packages

```
Package                   Version
------------------------- --------------------
appdirs                   1.4.4
attrs                     19.3.0
Automat                   0.8.0
awscli                    1.18.69
blinker                   1.4
botocore                  1.16.19
certifi                   2019.11.28
chardet                   3.0.4
Click                     7.0
cloud-init                23.2.1
colorama                  0.4.3
command-not-found         0.3
configobj                 5.0.6
consonance                0.1.5
constantly                15.1.0
cryptography              2.8
dbus-python               1.2.16
dissononce                0.34.3
distro                    1.4.0
distro-info               0.23+ubuntu1.1
docutils                  0.16
ec2-hibinit-agent         1.0.0
entrypoints               0.3
hibagent                  1.0.1
httplib2                  0.14.0
hyperlink                 19.0.0
idna                      2.8
importlib-metadata        1.5.0
incremental               16.10.1
iotop                     0.6
Jinja2                    2.10.1
jmespath                  0.9.4
jsonpatch                 1.22
jsonpointer               2.0
jsonschema                3.2.0
keyring                   18.0.1
language-selector         0.1
launchpadlib              1.10.13
lazr.restfulclient        0.14.2
lazr.uri                  1.0.3
MarkupSafe                1.1.0
more-itertools            4.2.0
netifaces                 0.10.4
oauthlib                  3.1.0
olefile                   0.46
pexpect                   4.6.0
Pillow                    7.0.0
pip                       20.0.2
protobuf                  3.19.4
pyasn1                    0.4.2
pyasn1-modules            0.2.1
Pygments                  2.3.1
PyGObject                 3.36.0
PyHamcrest                1.9.0
PyJWT                     1.7.1
pymacaroons               0.13.0
PyNaCl                    1.3.0
pyOpenSSL                 19.0.0
pyrsistent                0.15.5
pyserial                  3.4
python-apt                2.0.1+ubuntu0.20.4.1
python-axolotl            0.2.2
python-axolotl-curve25519 0.4.1.post2
python-dateutil           2.7.3
python-debian             0.1.36+ubuntu1.1
PyYAML                    5.3.1
requests                  2.22.0
requests-unixsocket       0.2.0
roman                     2.0.0
rsa                       4.0
s3transfer                0.3.3
SecretStorage             2.3.1
service-identity          18.1.0
setuptools                45.2.0
simplejson                3.16.0
six                       1.10.0
sos                       4.4
ssh-import-id             5.10
systemd-python            234
transitions               0.8.11
Twisted                   18.9.0
ubuntu-advantage-tools    8001
ufw                       0.36
unattended-upgrades       0.1
urllib3                   1.25.8
wadllib                   1.3.3
wheel                     0.34.2
zipp                      1.0.0
zope.interface            4.7.1
```

**Comment by holmanb** [comment] 2024-04-27 08:31
We weren't able to reproduce this issue, and do note that cloud-init should be using systemd dependencies, not pip installed dependencies.

It doesn't appear as if there is any issue with cloud-init, so closing for now. Please reopen with more information if you still believe this to be a bug.

**Closed** 2024-04-27 08:32 UTC
Labels: incomplete, bug
