### ISSUE TITLE
cloud-init schema validation fail

### ISSUE THREAD

**Issue by lb1021** [canonical/cloud-init#5571] opened 2024-07-31 06:18 UTC
# Bug report

We are trying to using OpenStack heat template including cloud-init to create instances. After create, we find Warning
Invalid network-config provided.
Actually the network-config.json is created by cloud-init, but it fail to validate by cloud-init.

## Environment details
- Cloud-init version: 23.4-7
- Operating System Distribution: RHEL 8.10
- Cloud provider, platform or installer type: OpenStack

## cloud-init logs

2024-06-24 07:16:01,074 - schema.py[WARNING]: Invalid network-config provided:
config.0.subnets.0: Additional properties are not allowed ('ipv4' was unexpected)
2024-06-24 07:16:01,106 - stages.py[INFO]: Applying network configuration from ds bringup=False: {'version': 1, 'config': [{'t
ype': 'physical', 'mtu': 1442, 'subnets': [{'type': 'static', 'netmask': '255.255.255.0', 'routes': [], 'address': '192.168.0.
105', 'ipv4': True}], 'mac_address': 'fc:26:2e:ea:12:1a', 'name': 'eth0'}, {'type': 'physical', 'mtu': 1442, 'subnets': [{'typ
e': 'dhcp4'}], 'mac_address': 'fc:26:2e:03:68:7e', 'name': 'eth1'}]}
2024-06-24 07:16:09,501 - main.py[INFO]: PID [1] started cloud-init.
2024-06-24 07:16:09,867 - schema.py[WARNING]: Invalid cloud-config provided: Please run 'sudo cloud-init schema --system' to see the schema errors.

network-config.json
```
{
   "version":1,
   "config":[
      {
         "type":"physical",
         "mtu":1442,
         "subnets":[
            {
               "type":"static",
               "netmask":"255.255.255.0",
               "routes":[],
               "address":"192.168.0.105",
               "ipv4":true
            }
         ],
         "mac_address":"fc:26:2e:ea:12:1a",
         "name":"eth0"
      },
      {
         "type":"physical",
         "mtu":1442,
         "subnets":[
            {
               "type":"dhcp4"
            }
         ],
         "mac_address":"fc:26:2e:03:68:7e",
         "name":"eth1"
      }
   ]
}
```

**Comment by a-dubs** [comment] 2024-08-08 21:38
by applying the following patch on to tip of main:
```
diff --git a/tests/unittests/config/test_schema.py b/tests/unittests/config/test_schema.py
index 184857583..3fd65bbaa 100644
--- a/tests/unittests/config/test_schema.py
+++ b/tests/unittests/config/test_schema.py
@@ -2548,6 +2548,27 @@ class TestNetworkSchema:
                 "",
                 id="GH-4710_mtu_none_and_str_address",
             ),
+            pytest.param(
+                {
+                    "type":"physical",
+                    "mtu":1442,
+                    "subnets":[
+                        {
+                        "type":"static",
+                        "netmask":"255.255.255.0",
+                        "routes":[],
+                        "address":"192.168.0.105",
+                        "ipv4":True
+                        }
+                    ],
+                    "mac_address":"fc:26:2e:ea:12:1a",
+                    "name":"eth0"
+                },
+                SchemaType.NETWORK_CONFIG_V1,
+                does_not_raise(),
+                "",
+                id="GH-5571_ipv4_unexpected",
+            ),
         ),
     )
     @mock.patch("cloudinit.net.netplan.available", return_value=False)

```
and running:
```bash
tox -e py3 -- tests/unittests/config/test_schema.py::TestNetworkSchema::test_network_schema
```
I was able to confirm that `schema.py` properly handles this config and does not throw that error. So I assume that this was an issue that has since been fixed in more recent versions of cloud-init?? This definitely needs more investigating so am going to leave open for now.

**Comment by aciba90** [comment] 2024-08-20 09:52
Thanks, @MrStupnikov, for pointing out that the issue is already fixed. Closing as such, please re-open if needed.

**Closed by aciba90** 2024-08-20 09:52 UTC
Labels: bug
