### ISSUE TITLE
cloud-init changes behaviour with ubuntu cloud image ova starting from version 20230602

### ISSUE THREAD

**Issue by lethargosapatheia** [canonical/cloud-init#4188] opened 2023-06-15 11:59 UTC
# Bug report
Since the Ubuntu 22.04 **20230602** (https://cloud-images.ubuntu.com/jammy/20230602/) cloud image version (tested on OVA) the behaviour of cloudinit has changed. Until this version appeared the virtual machine would start, apply the cloudinit settings, but it wouldn't boot fully, that is to say, I wasn't getting a login prompt and, more importantly, the SSH server didn't start. This is the expected behaviour.

Since **20230602** this behaviour has unexpectedly changed. In this intermediary phase, the virtual machine does boot fully, I get a login prompt and the SSH starts. 

For me this looks like a bug, because I expect the SSH server not to start before all the cloud-init settings have been applied, meaning, before the virtual machine actually reboots.

Of course, this behaviour completely disturbs automatic provisioning with tools like Packer, which rely on SSH server being available at the right time, when everything is ready. In my case, packer (1.7.9) starts doing the provisioning through ansible (2.14.6) and it's interrupted by the reboot, making it impossible to automate the process.

I can confirm the provisioning works properly with version **20230524** (https://cloud-images.ubuntu.com/jammy/20230524/) of Ubuntu 22.04, where the VM doesn't boot fully and restarts correctly, without starting the SSH server before rebooting.

I am using vSphere 6.7.0.54000 to provision my virtual machines.

## Environment details
- Cloud-init version on both cloudimage versions:
```
ii  cloud-guest-utils               0.32-22-g45fe84a5-0ubuntu1              all          cloud guest utilities
ii  cloud-init                      23.1.2-0ubuntu0~22.04.1                 all          initialization and customization tool for cloud instances
ii  cloud-initramfs-copymods        0.47ubuntu1                             all          copy initramfs modules into root filesystem for later use
ii  cloud-initramfs-dyn-netconf     0.47ubuntu1                             all          write a network interface file in /run for BOOTIF
```
- Operating System Distribution: Ubuntu 22.04.2
- Cloud provider, platform or installer type: vSphere/OVA

## cloud-init logs

I'm uploading the cloudinit logs for both images using `cloud-init collect-logs` and those from `var/log/cloud-init.log`.

[cloud-init-20230602.tar.gz](https://github.com/canonical/cloud-init/files/11757128/cloud-init-20230602.tar.gz)
[var-log-cloud-init-20230602.tar.gz](https://github.com/canonical/cloud-init/files/11757129/var-log-cloud-init-20230602.tar.gz)

[cloud-init-20230524.tar.gz](https://github.com/canonical/cloud-init/files/11757124/cloud-init-20230524.tar.gz)
[var-log-cloud-init-20230524.tar.gz](https://github.com/canonical/cloud-init/files/11757125/var-log-cloud-init-20230524.tar.gz)

Please let me know if I need to add any information.

Best regards!

**Comment by blackboxsw** [comment] 2023-06-15 16:50
Thank you @lethargosapatheia for filing a bug and trying to improve cloud-init. Given that cloud-init is the same version in both images it is highly unlikely that cloud-init is the problem, but something outside of cloud-init in images affecting the behavior you are seeing with login prompt changes and reboots.

The initial difference I see in cloud-init behavior between 5/24 and 06/02 is that the first boot in 0524 only runs cloud-init's `init-local` stage (you can see the boot stages run per boot with `cloud-init analyze show` which exits with a NOOP with the message in /var/log/cloud-init.log: 
```
2023-06-15 11:47:06,317 - main.py[DEBUG]: [local] Exiting. datasource DataSourceOVF [seed=iso] not in local mode.
```


On 0602 image that first boot actually runs both `init-local` and `init` stages, so an additional  cloud-init stage was able to run on 0602 images that wasn't run on 0524.

Something seems to have triggered reboot of the machine later on 0624, or for some reason systemd didn't include `cloud-init.service` as a boot goal in the earlier 0524 image first boot.  

Unfortunately, the journal.txt included by default in cloud-init  collect-logs is only the most recent boot (from journalctl -b 0) what I think we'd need to see is journalctl -b 1 output from both images. that'll give us service information run on previous boot to make sure there isn't some sort of systemd ordering cycle that kicked out cloud-init system services from the boot goals.

**Comment by lethargosapatheia** [comment] 2023-06-15 21:09
Thank you for your fast response. I'm adding here the two logs (these are newly created templates using the same two images, but I'm guessing it shouldn't be a problem, as the behaviour is consistent).
Let me know if this is provides enough information.
[journald-b1-20230602.log](https://github.com/canonical/cloud-init/files/11763340/journald-b1-20230602.log)
[journal-b1-20230524.log](https://github.com/canonical/cloud-init/files/11763341/journal-b1-20230524.log)

**Comment by lethargosapatheia** [comment] 2023-06-26 20:47
Ok, I seem to have found the solution. I was able to tell cloud-init to stop the ssh service only once, before rebooting, and then not run the command again, as it did when simply running `bootcmd`:
```yaml
bootcmd:
  - [ cloud-init-per, once, systemctl, stop, sshd ]
```

**Comment by holmanb** [comment] 2023-06-29 14:03
> Ok, I seem to have found the solution. 

Glad you found a workaround to your issue. I'm going to close this issue. Please reopen with more details if you see further issue related to cloud-init.

**Closed by holmanb** 2023-06-29 14:03 UTC
Labels: incomplete, bug

**Comment by holmanb** [comment] 2023-06-29 21:48
> cloudinit has changed its behaviour in the ova ubuntu cloudimages

Are you sure? @blackboxsw already pointed out that this is the same version of cloud-init, so I'd be surprised if it was a cloud-init behavior change.

**Something** changed, agreed. Perhaps a service that cloud-init depends on didn't start for some reason?

**Comment by lethargosapatheia** [comment] 2023-06-30 10:24
Well, initially I mentioned this on the #ubuntu-server (not on the cloud-init one) irc channel and @blackboxsw told me that I should file a bug here, which I was a little bit surprised of, also because he himself said that he suspected the cloud-init versions are the same.

I also kind of expected a feedback related to the logs that I added afterwards, but I guess there's nothing to infer from there, as far as I understand, so I'm putting it down to a lack of communication.

That said, where could I then file a bug related to this issue?

**Comment by lethargosapatheia** [comment] 2023-07-27 16:17
I'm still at a loss as to why this issue is ignored. The change is really important and no one seems to be bothered by this. I've actually underestimated the issue, because this doesn't only affect the packer templates. When cloning them and using cloud-init again, I get the same behaviour where the virtual machine restarts after terraform connects to it.

**Comment by lethargosapatheia** [comment] 2023-07-28 20:07
This seems to be related to vmtools (perl guest os costumization in vSphere) which by default reboots the virtual machine after cloud-init is finished. It's kind of a mess and rather difficult to get rid of.

**Comment by vitality411** [comment] 2023-08-28 05:37
Hello @lethargosapatheia, 
thanks to you and this issue I was able to find out the cause for my issues with Ubuntu 22.04 [20230602](https://cloud-images.ubuntu.com/releases/jammy/release-20230602/ubuntu-22.04-server-cloudimg-amd64.ova) cloud image and newer. Please see the linked issue in the open-vm-tools repo for details. I am certain that it is also the cause for this issue. As a workaroud I set wait-cloudinit-timeout to 0 in order to archive the previous behaviour in my cloud-init userdata:

```
bootcmd:
    - echo '[deployPkg]\nwait-cloudinit-timeout=0' >> /etc/vmware-tools/tools.conf
```

Best regards

**Comment by lethargosapatheia** [comment] 2023-08-28 06:37
Hi @vitality411. Thanks for reaching back!
I also wrote about the issue on the vmware forums (https://communities.vmware.com/t5/Virtual-Machine-Guest-OS-and-VM/how-to-turn-off-vm-toools-rebooting-ubuntu-VM-based-on/m-p/2979757#M49207), but there was no reply. Posting on github, like you did, is probably a better idea, indeed.

What I ended up doing was completely removing the symlink `/sbin/` that the vmware tools use in order to reboot the server. vmware-tools complains that it doesn't find the command andthat's about it. It's a horrid solution to my mind, but it was the necessary at the point.

Your solution seems much more elegant, of course, because at least it hopefully observes the logic of vmware tools.
Can you explain the consequences of your solution? Intuitively I'd expect it to mean vmware-tools won't wait for cloud-init to finish at all and it would restart immediately, but I'm guessing it doesn't do that, right? Does it simply stop it from rebooting the system?

**Comment by vitality411** [comment] 2023-08-28 10:53
> order to archive the previous behaviour in my cloud-init userdata:
> 
> ```
> bootcmd:
>     - echo '[deployPkg]\nwait-cloudinit-timeout=0' >> /etc/vmware-tools/tools.conf
> ```

I have to correct my workaroud. This does not work on an upstream image as open-vm-tools.service starts before cloud-init and so is running with the default timeout (30s). The only working workaround I have is building my own image with wait-cloudinit-timeout=0 already set.

**Comment by lethargosapatheia** [comment] 2023-08-31 09:26
For me changing the cloudimage beforehand is a no-go. That's exactly why I use the cloud-image, so that I have a baseline image that I can change afterwards as I like, without having to edit it beforehand and that's the reason why I switched from ubuntu iso images where I'd go through the whole install process to the cloud-image. I also rely on the updates that cloud-images provide and the image is ready-made.

I know this has become rather off-topic, but I think this is important for people who come across this issue nonetheless.

**Comment by vitality411** [comment] 2023-08-31 09:30
I couldn't agree more. For me changing cloudimage beforehand is also a no-go.
