### ISSUE TITLE
"failed stage init-local" while testing autoinstall on Noble

### ISSUE THREAD

**Issue by p-gentili** [canonical/cloud-init#4630] opened 2023-11-27 16:56 UTC
# Bug report
I can't make _autoinstall_ work on the latest Noble image. I can see tracebacks in the _cloud-init.log_ and, as a result, _subiquity_ doesn't not recognize _autoinstall_ was provided.

I tested both USB and HTTP methods for provisioning _autoinstall_ configuration files but no luck in both cases. The logs below refers to the HTTP test.

## Steps to reproduce the problem

- Flash the [latest](https://cdimage.ubuntu.com/daily-live/20231127/) amd64 Noble ISO
- Host this user-data file over HTTP 
```
#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ai-test
    password: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
    username: ubuntu
  ssh:
    install-server: true
  storage:
    layout:
      name: hybrid
```
- Modify cmdline as explained in https://ubuntu.com/server/docs/install/autoinstall-quickstart

Apart from this test, I've also tested both the basic examples in [here](https://ubuntu.com/server/docs/install/autoinstall-quickstart
) without success.

## Environment details
- Cloud-init version: 23.4~3g0cb0b80f-0ubuntu1
- Operating System Distribution: Ubuntu Noble
- Cloud provider, platform or installer type: amd64 ISO

## cloud-init logs
```
2023-11-27 16:00:45,678 - util.py[DEBUG]: failed stage init-local
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 386, in main_init
    init.fetch(existing=existing)
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 469, in fetch
    return self._get_data_source(existing=existing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 360, in _get_data_source
    (ds, dsname) = sources.find_source(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 1028, in find_source
    raise DataSourceNotFoundException(msg)
cloudinit.sources.DataSourceNotFoundException: Did not find any data source, searched classes: (DataSourceNoCloud)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 772, in status_wrapper
    ret = functor(name, args)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 407, in main_init
    init.apply_network_config(bring_up=bring_up_interfaces)
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 1026, in apply_network_config
    self._apply_netcfg_names(netcfg)
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 948, in _apply_netcfg_names
    atomic_helper.write_json(
  File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 89, in write_json
    return write_file(
           ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 65, in write_file
    raise e
  File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 46, in write_file
    tf = tempfile.NamedTemporaryFile(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 702, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 699, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 395, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/cloud/instance/tmpmxvzqpqp'
```

**Comment by blackboxsw** [comment] 2023-11-28 16:15
I can reproduce this on Nobel server-live images in manual install case as well. Marking this as needed for 23.4. Investigating the source of the issue here and we want to ensure this is resolved/understood before we release cloud-init 23.4.

**Comment by blackboxsw** [comment] 2023-11-28 17:34
Ok, the issue was introduced in this commit ee86a37fef and affects any datasource detected only in the init-Network boot stage. When no datasource is discovered/detected during the Local boot stage, cloud-init still calls apply_network_config to emit a basic dhcp on primary NIC configuration prior to system networking being brought up. Due to the above commit, cloud-init also attempts to write the generated network configuration dictionary to the expected symlink: /var/lib/cloud/instance/network-config.json. In the Local boot stage, when no datasource is yet detected, the symlink doesn't yet exist at `/var/lib/cloud/instance/`. So, we need to ensure that cloud-init doesn't try to write out that network-config.json file yet, it should wait until a proper datasource is detected first.

**Closed** 2023-11-30 22:44 UTC
Labels: bug, priority, 23.4
