### ISSUE TITLE
cloud-init failed saying  IsADirectoryError: [Errno 21] Is a directory: '/var/lib/cloud/instance'

### ISSUE THREAD

**Issue by v-nightwolf** [canonical/cloud-init#4282] opened 2023-07-24 07:46 UTC
# Bug report

cloud-init failed to start.
Further checked and found "/var/lib/cloud/instance" to be a directory. Ideally /var/lib/cloud/instance should be a symlink to a directory named ${VM-ID} in same location. 

## Steps to reproduce the problem

Customer created the instance using snapshot of an existing VM and then again new vm created from snapshot of earlier created VM. Somehow the  "/var/lib/cloud/instance" changed to directory which caused the failure with cloud-init. 

We manually removed the " "/var/lib/cloud/instance" " and then tried `cloud-init init` and it worked fine. 

Ideally if /var/lib/cloud/instance is a directory, then cloud init should remove it and then create a symlink pointing  to a directory named with ${VM-ID} in same location. 

## Environment details
- Cloud-init version: 23.1.2-0ubuntu0~20.04.2
- Operating System Distribution: Ubuntu 20.04
- Cloud provider, platform or installer type: GCP

## cloud-init logs

`
[   11.998252] cloud-init[717]: Cloud-init v. 23.1.2-0ubuntu0~20.04.2 running 'init-local' at Wed, 12 Jul 2023 11:18:54 +0000. Up 11.96 seconds.
[   12.022066] cloud-init[717]: 2023-07-12 11:18:54,668 - [util.py](https://util.py/)[WARNING]: failed stage init-local
[   12.042079] cloud-init[717]: failed run of stage init-local
[[0;1;31mFAILED[0m] Failed to start [0;1;39mInitial cloud-init job (pre-networking)[0m.
[   12.058094] cloud-init[717]: ------------------------------------------------------------
See 'systemctl status cloud-init-local.service' for details.
[   12.082105] cloud-init[717]: Traceback (most recent call last):
[[0;32m  OK  [0m] Reached target [0;1;39mNetwork (Pre)[0m.
[   12.114084] cloud-init[717]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/[main.py](https://main.py/)", line 767, in status_wrapper
         Starting [0;1;39mNetwork Service[0m...
[   12.150067] cloud-init[717]:     ret = functor(name, args)
[   12.182067] cloud-init[717]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/[main.py](https://main.py/)", line 362, in main_init
[   12.202103] cloud-init[717]:     purge_cache_on_python_version_change(init)
[   12.222094] cloud-init[717]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/[main.py](https://main.py/)", line 274, in purge_cache_on_python_version_change
[   12.246111] cloud-init[717]:     init.purge_cache(True)
[[0;32m  OK  [0m] Started [0;1;39mNetwork Service[0m.
[   12.262056] cloud-init[717]:   File "/usr/lib/python3/dist-packages/cloudinit/[stages.py](https://stages.py/)", line 196, in purge_cache
         Starting [0;1;39mWait for Network to be Configured[0m...
[   12.298047] cloud-init[717]:     util.del_file(f)
         Starting [0;1;39mNetwork Name Resolution[0m...
[   12.330034] cloud-init[717]:   File "/usr/lib/python3/dist-packages/cloudinit/[util.py](https://util.py/)", line 2001, in del_file
[[0;32m  OK  [0m] Finished [0;1;39mWait for Network to be Configured[0m.
[   12.370114] cloud-init[717]:     raise e
         Starting [0;1;39mInitial cloud-ini… (metadata service crawler)[0m...
[   12.398112] cloud-init[717]:   File "/usr/lib/python3/dist-packages/cloudinit/[util.py](https://util.py/)", line 1998, in del_file
[   12.434175] cloud-init[717]:     os.unlink(path)
[   12.454186] cloud-init[717]: IsADirectoryError: [Errno 21] Is a directory: '/var/lib/cloud/instance'
[   12.474177] cloud-init[717]: ------------------------------------------------------------
`

**Comment by aciba90** [comment] 2023-07-27 12:56
Thanks @v-nightwolf for reporting this.

Yes, `/var/lib/cloud/instance` must be a symlink in every case.

> Somehow the "/var/lib/cloud/instance" changed to directory

I think the key point is the _somehow_. If cloud-init cause that change, then it is a bug. If that was changed by the user or an external system, then I do not think it is a bug. As it would be hard to handle and maintain each and every combination of file / directory / symlink changes for cloud-init internal files.

That said, if the user wants to create a snapshot and let cloud-init run as first boot, then they should execute [cloud-init clean](https://canonical-cloud-init.readthedocs-hosted.com/en/latest/reference/cli.html#clean) before creating the snapshot.

If you still think this is an issue, please, explain how can we reproduce it and attach the full [logs](https://canonical-cloud-init.readthedocs-hosted.com/en/latest/reference/cli.html#collect-logs)

**Comment by holmanb** [comment] 2024-07-23 20:02
Can't reproduce, closing.

**Closed by holmanb** 2024-07-23 20:02 UTC
Labels: bug, invalid
