### ISSUE TITLE
Error loading cloud-init config: bad file - multipass and cloud-init

### ISSUE THREAD

**Issue by tersucorp** [canonical/cloud-init#5737] opened 2024-09-24 13:55 UTC
# Bug report
I get the error below when trying to create vms with multipass and cloud init.
```
error loading cloud-init config: bad file
error loading cloud-init config: bad file
error loading cloud-init config: bad file
error loading cloud-init config: bad file
```

**To Reproduce**
1. install multipass `1.14.0`
2. install cloud init `24.2-0ubuntu1~24.04.2`
3. create a cloud-init config file in config/debian-cloud-init.yaml:
```
#cloud-config
package_update: true
packages:
  - debootstrap
users:
  - name: root
    lock_passwd: false
    passwd: tersu
ssh_pwauth: true
disable_root: false
runcmd:
  - debootstrap --arch=arm64 bookworm /mnt http://deb.debian.org/debian/
  - mount --bind /dev /mnt/dev
  - mount --bind /proc /mnt/proc
  - mount --bind /sys /mnt/sys
  - |
      chroot /mnt /bin/bash -c "apt-get update && \
      apt-get install -y linux-image-arm64 systemd-sysv"
  - chroot /mnt /bin/bash -c "apt-get install -y grub-efi"
  - |
      chroot /mnt /bin/bash -c "grub-install --target=arm64-efi \
      --efi-directory=/boot/efi --bootloader-debian --recheck"
  - chroot /mnt /bin/bash -c "update-grub"
  - |
      chroot /mnt /bin/bash -c "echo 'deb http://deb.debian.org/debian/ \
      bookworm main' > /etc/apt/sources.list"
  - chroot /mnt /bin/bash -c "echo 'root:password' | chpasswd"
  - |
      chroot /mnt /bin/bash -c "sed -i 's/^#PermitRootLogin.*/\
      PermitRootLogin yes/' /etc/ssh/sshd_config"
  - chroot /mnt /bin/bash -c "systemctl enable ssh"
  - umount /mnt/dev
  - umount /mnt/proc
  - umount /mnt/sys
  - echo "Debian installation completed!"
```

4. Create a bash script to create vms using multipass and cloud-init
```
#!/bin/bash

# Launch VMs with multipass
multipass launch --name jumpbox --cpus 1 --memory 512M --disk 5G --cloud-init ./config/debian-cloud-init.yaml --verbose
multipass launch --name master --cpus 1 --memory 2G --disk 10G --cloud-init ./config/debian-cloud-init.yaml --verbose
multipass launch --name worker1 --cpus 1 --memory 2G --disk 10G --cloud-init ./config/debian-cloud-init.yaml --verbose
multipass launch --name workder2 --cpus 1 --memory 2G --disk 10G --cloud-init ./config/debian-cloud-init.yaml --verbose
```

5. Run the bash script

**Expected behavior**
It should create the multipass VMs with the specified config

## cloud-init logs
[cloud-init.tar.gz](https://github.com/user-attachments/files/17115679/cloud-init.tar.gz)

**Comment by holmanb** [comment] 2024-09-24 15:43
@tersucorp Cloud-init appears to work just fine on multipass using an image provided by multipass:
```
$ cloud-init --version
/usr/bin/cloud-init 24.2-0ubuntu1~24.04.2
``` 
I think that this is an error in your image build process.

It looks like ds-identify didn't find a datasource. On a good launch of cloud-init I see this in `/run/cloud/ds-identify.log`:
```
ISO9660_DEVS=/dev/sr0=cidata
```

but on yours I see:
```
ISO9660_DEVS=
```

So it looks like multipass isn't providing the user-data disk for some reason.

**Comment by tersucorp** [comment] 2024-09-24 21:00
@holmanb yes, I checked the validity of the file:

```
cloud-init schema -c config/debian-cloud-init.yaml -t cloud-config                                                           21:58:40
Valid schema config/debian-cloud-init.yaml
```

````
yamllint config/debian-cloud-init.yaml                                                                                       21:58:45
config/debian-cloud-init.yaml
  1:2       warning  missing starting space in comment  (comments)
  2:1       warning  missing document start "---"  (document-start)
```

I also want to add that I am running this from my local machine - ubuntu 24.04

**Comment by tersucorp** [comment] 2024-09-24 21:30
@holmanb  I also copied samples from here to test, and got the same error:

https://cloudinit.readthedocs.io/en/latest/reference/examples.html

**Comment by holmanb** [comment] 2024-09-24 22:01
@tersucorp It works for me with your config.

```bash
$ multipass launch --name master --cloud-init ./debian-cloud-init.yaml --verbose
Launched: master
$ multipass --version                                                           
multipass   1.14.0
multipassd  1.14.0
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

$ cat ./debian-cloud-init.yaml 
#cloud-config
package_update: true
packages:
  - debootstrap
users:
  - name: root
    lock_passwd: false
    passwd: tersu
ssh_pwauth: true
disable_root: false
runcmd:
  - debootstrap --arch=arm64 bookworm /mnt http://deb.debian.org/debian/
  - mount --bind /dev /mnt/dev
  - mount --bind /proc /mnt/proc
  - mount --bind /sys /mnt/sys
  - |
      chroot /mnt /bin/bash -c "apt-get update && \
      apt-get install -y linux-image-arm64 systemd-sysv"
  - chroot /mnt /bin/bash -c "apt-get install -y grub-efi"
  - |
      chroot /mnt /bin/bash -c "grub-install --target=arm64-efi \
      --efi-directory=/boot/efi --bootloader-debian --recheck"
  - chroot /mnt /bin/bash -c "update-grub"
  - |
      chroot /mnt /bin/bash -c "echo 'deb http://deb.debian.org/debian/ \
      bookworm main' > /etc/apt/sources.list"
  - chroot /mnt /bin/bash -c "echo 'root:password' | chpasswd"
  - |
      chroot /mnt /bin/bash -c "sed -i 's/^#PermitRootLogin.*/\
      PermitRootLogin yes/' /etc/ssh/sshd_config"
  - chroot /mnt /bin/bash -c "systemctl enable ssh"
  - umount /mnt/dev
  - umount /mnt/proc
  - umount /mnt/sys
  - echo "Debian installation completed!"
```

**Comment by tersucorp** [comment] 2024-09-24 22:04
Wow! So how do I even begin to figure out what the issue is?

**Comment by holmanb** [comment] 2024-09-24 22:23
> Wow! So how do I even begin to figure out what the issue is?

@tersucorp When dealing with the unexpected like this, start by challenging your assumptions and expectations. Reinstall multipass. Delete the configuration files and scripts and recreate them. Does it still happen? Are you able to recreate my working example? If you're doing anything weird (building multipass from source, using custom images, etc), see if it reproduces with a more standard setup. If none of those steps identify your problem, then you should file a bug against multipass and see if they can help you.

**Comment by holmanb** [comment] 2024-09-24 22:27
@tersucorp This doesn't appear to be an issue with cloud-init, so I'm going to close it. Best of luck!

**Closed by holmanb** 2024-09-24 22:27 UTC
Labels: bug, invalid

**Comment by holmanb** [comment] 2024-10-10 15:49
See the resolution of this issue [here](https://github.com/canonical/multipass/issues/3693).
