### ISSUE TITLE
Previously working configuration on Amazon Linux 2 no longer works on Amazon Linux 2023

### ISSUE THREAD

**Issue by hahuang65** [canonical/cloud-init#5533] opened 2024-07-22 20:14 UTC
# Bug report

Previous set-up that worked on Amazon Linux 2 no longer works on Amazon Linux 2023
Specifically, `runcmd` isn't run, while everything else is... even though logs seem to reflect that nothing was run. The version of cloudinit that was working on Amazon Linux 2 is `19.3-46.amzn2.0.1`

I have a setup that uses [packer](https://www.packer.io) to create an AMI, then uses Terraform to start an EC2 instance using that AMI. The issue occurs when Terraform starts the EC2 instance. The ultimate issue is that my `runcmd` sections are not run.

When `packer` is run, I do not have any user-data. All the user-data is applied thru Terraform.

Some interesting things I've noticed:

1) cloud-init logs state that it's symlinking, but it doesn't actually do it
```
2024-07-22 18:04:54,076 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-0d45a58160fcd4eea'
```

```
$ ls -a1 /var/lib/cloud
.
..
data
instances
sem

$ ls -a1 /var/lib/cloud/instances/
.
..
i-0d45a58160fcd4eea
iid-datasource-none
```

2) cloud-init logs says that it is downloading user-data, but doesn't
```
2024-07-22 18:04:53,787 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/user-data (200, 12342b) after 1 attempts
2024-07-22 18:04:54,268 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d45a58160fcd4eea/user-data.txt - wb: [600] 12342 bytes
```

```
$ ls /var/lib/cloud/instances/i-0d45a58160fcd4eea/user-data.txt
ls: cannot access '/var/lib/cloud/instances/i-0d45a58160fcd4eea/user-data.txt': No such file or directory
```

3) Other parts of my user data are run... These examples show that `packages`, `users`, `write_files` and `bootcmd` are working:

```
$ which jq
/usr/bin/jq

$ which mosh
/usr/local/bin/mosh

$ which aws
/usr/bin/aws
```

```
$ whoami
hhhuang
```

```
$ cat /usr/local/sbin/ec2-hostname.sh
#!/bin/bash

REGION=$(curl -s \
  http://169.254.169.254/latest/dynamic/instance-identity/document | \
  jq .region -r)
INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
NAME_TAG=$(aws ec2 describe-tags \
           --region ${REGION}    \
           --filters Name=resource-id,Values=${INSTANCE_ID} Name=key,Values=Name \
           --output=text|cut -f5)
HOST=${NAME_TAG}.mydomain
echo ${HOST} > /etc/hostname
hostname ${HOST}
```

```
$ sudo ls /root/
cloud-init-ebs-mounted
```

# user-data

### Note that this is the `/var/lib/cloud/instance/user-data.txt` from a working machine (Amazon Linux 2). It's generated via Terraform's [cloudinit_config](https://registry.terraform.io/providers/hashicorp/cloudinit/latest/docs/data-sources/config) via a few different yaml part files. I am on the latest version of this Terraform provider, which is 2.3.4 as of this writing.

```
Content-Type: multipart/mixed; boundary="MIMEBOUNDARY"
MIME-Version: 1.0

--MIMEBOUNDARY
Content-Transfer-Encoding: 7bit
Content-Type: text/plain
Mime-Version: 1.0
X-Merge-Type: list(append)+dict(recurse_array)+str()

#cloud-config

# NOTE: This file is also duplicated in the summit-partners/terraform-infra repository.
# Eventually we want to unify both places so we don't have to remember to
# update in multiple places. Perhaps backing this into the AMI is a good idea.

# This is common to all EC2 instances
# -  mount an EBS volume to /data and move /var/log and /var/lib under
#    the /data directory.

repo_update: true
repo_upgrade: all

# Lets us override hostname via scripts
preserve_hostname: true

packages:
  - mosh
  - zsh
  - jq
  - ack
  - aws-cli

users:
  - default

bootcmd:
  - set -ex
  - test -d /data || mkdir /data
  - |
    if [ ! -f /root/cloud-init-ebs-mounted ]; then
      mkfs.ext4 /dev/nvme1n1
      mount -t ext4 -o noatime /dev/nvme1n1 /data
      mkdir /data/var
      mv /var/lib /data/var && ln -s /data/var/lib /var/lib
      mv /var/log /data/var && ln -s /data/var/log /var/log
    fi
  - touch /root/cloud-init-ebs-mounted

write_files:
  - path: /usr/local/sbin/ec2-hostname.sh
    permissions: '0755'
    content: |
      #!/bin/bash

      REGION=$(curl -s \
        http://169.254.169.254/latest/dynamic/instance-identity/document | \
        jq .region -r)
      INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
      NAME_TAG=$(aws ec2 describe-tags \
                 --region ${REGION}    \
                 --filters Name=resource-id,Values=${INSTANCE_ID} Name=key,Values=Name \
                 --output=text|cut -f5)
      HOST=${NAME_TAG}.mydomain
      echo ${HOST} > /etc/hostname
      hostname ${HOST}

runcmd:
  # Set hostname
  - echo /usr/local/sbin/ec2-hostname.sh >> /etc/rc.local
  - /usr/local/sbin/ec2-hostname.sh
  # Restart the datadog-agent if it's installed so it picks up the new hostname
  - systemctl restart datadog-agent
  - touch /root/cloud-init-base-complete

mounts:
  - [ /dev/nvme1n1, /data, ext4 ]

merge_type: 'list(append)+dict(recurse_array)+str()'

--MIMEBOUNDARY
Content-Transfer-Encoding: 7bit
Content-Type: text/plain
Mime-Version: 1.0
X-Merge-Type: list(append)+dict(recurse_array)+str()

#cloud-config

# Pre-requisite: Rails AMI, parts/base.yaml
#
# This config will:
# - Install CRM user

users:
  - name: crm
    shell: /bin/zsh
    homedir: /data/crm
    sudo:
      - ALL=(ALL) NOPASSWD:ALL

write_files:
  - content: |
      test -d current && cd current
    permissions: '0644'
    path: /data/crm/.zshrc
  - content: |
      RAILS_ENV=production
      RACK_ENV=production
      NODE_ENV=production

      # This affects DB pool size.
      MAX_THREADS=16
      SHORYUKEN_WORKERS=20

      # MAX_THREADS + SHORYUKEN_WORKERS, probably overkill
      DB_POOL=36

      ESBULK_BIN=/usr/local/sbin/esbulk

    permissions: '0644'
    path: /data/crm/.rbenv-vars
  - content: |
      require 'irb/ext/save-history'
      IRB.conf[:SAVE_HISTORY] = 200
      IRB.conf[:HISTORY_FILE] = "#{ENV['HOME']}/.irb-history"
    permissions: '0644'
    path: /data/crm/.irbc
  - content: |
      --modules-folder /data/crm/node_modules
    permissions: '0644'
    path: /data/crm/.yarnrc

# This gets run once.
runcmd:
  - set -ex
  # Setup crm
  # Start codedeploy-agent when this is all set.
  # This is for ASGs as those deploy immediately and don't wait for cloudinit to finish
  # This will make sure everything is set up before CodeDeploy can do any deployments.
  - mkdir -p /data/crm/versions
  - mkdir /data/crm/assets
  - mkdir /data/crm/bundle
  - mkdir /data/crm/node_modules
  - mkdir /data/crm/log
  - chown -R crm:crm /data/crm
  - sudo systemctl enable --now codedeploy-agent
  - touch /root/cloud-init-rails-runcmd-complete

--MIMEBOUNDARY


# This gets run once.
runcmd:
  - set -ex

    # To make tcp retries happen faster so RDS failovers can work
  - echo 'net.ipv4.tcp_retries2 = 5' >> /etc/sysctl.conf
  - sysctl -p /etc/sysctl.conf
  - systemctl enable --now nginx

  - touch /root/cloud-init-rails-service-runcmd-complete


--MIMEBOUNDARY
Content-Transfer-Encoding: 7bit
Content-Type: text/plain
Mime-Version: 1.0
X-Merge-Type: list(append)+dict(recurse_array)+str()

#cloud-config

# - Keys are sourced from github.com/$username.keys

users:
  - name: hhhuang
    gecos: Howard Huang
    groups: users
    lock-passwd: true
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK/ZETjVqLZ+cSU2KK6oDbuhSkhrBhPjHK02vEXnGyDW

--MIMEBOUNDARY--
```

## Environment details
- Cloud-init version: 22.2.2
- Operating System Distribution: Amazon Linux 2023 `6.1.96-102.177.amzn2023.aarch64`
- Cloud provider, platform or installer type:

## cloud-init logs

This was too long to paste, so it is here: https://gist.github.com/hahuang65/2edf733696aa2b38db4c765f6e2c4982

**Comment by hahuang65** [comment] 2024-07-22 20:18
This may or may not be related:

https://stackoverflow.com/questions/78769521/cloud-init-fails-on-amazon-linux-2023-but-works-on-amazonlinux2

https://repost.aws/questions/QUFWDJ6WFSSzarr2GeW0Td_w/cloud-init-script-is-not-being-run-on-amazon-linux-2023

**Comment by hahuang65** [comment] 2024-07-22 20:19
Also, I originally thought (since only `runcmd` wasn't working) that this was my issue:
https://www.virtualthoughts.co.uk/2023/01/18/debugging-cloud-init-not-executing-runcmd-commands/

But it's not.

**Comment by hahuang65** [comment] 2024-07-22 20:25
If I copy `/var/lib/cloud/instance/user-data.txt` from my Amazon Linux 2 machine to the Amazon Linux 2023 machine, and run `sudo cloud-init schema --system --annotate`, it tells me

```
# E1: File None needs to begin with "#cloud-config"
```

On the Amazon Linux 2 machine, where cloudinit is v19.x.x, `cloud-init schema` isn't even a sub-command. Might this be the issue? But even if so, this doesn't explain why parts of my user-data are actually run.

**Comment by aciba90** [comment] 2024-07-23 09:23
> Might this be the issue? But even if so, this doesn't explain why parts of my user-data are actually run.

I think you are right, there are multiple issues going on here.

Regarding `runcmd` not being run, I believe that the issue is that some of you config parts is overwriting the others. Your config is composed by several parts (divided by `--MIMEBOUNDARY`) and the penultimate does not specify a special [merge strategy](https://docs.cloud-init.io/en/latest/reference/merging.html) and overwrite the others' runcmd stanzas. Could you please try modifying that part to be:

```
--MIMEBOUNDARY
Content-Transfer-Encoding: 7bit
Content-Type: text/plain
Mime-Version: 1.0
X-Merge-Type: list(append)+dict(recurse_array)+str()

#cloud-config

# This gets run once.
runcmd:
  - set -ex

    # To make tcp retries happen faster so RDS failovers can work
  - echo 'net.ipv4.tcp_retries2 = 5' >> /etc/sysctl.conf
  - sysctl -p /etc/sysctl.conf
  - systemctl enable --now nginx

  - touch /root/cloud-init-rails-service-runcmd-complete
```

The not compliant schema error is because that config part did not contain the `#cloud-init` header, I believe.

Could you please attach the full output of `cloud-init collect-logs`, making sure any sensitive information is redacted?

**Comment by hahuang65** [comment] 2024-07-23 16:54
> Regarding `runcmd` not being run, I believe that the issue is that some of you config parts is overwriting the others. Your config is composed by several parts (divided by `--MIMEBOUNDARY`) and the penultimate does not specify a special [merge strategy](https://docs.cloud-init.io/en/latest/reference/merging.html) and overwrite the others' runcmd stanzas.

This was it. I didn't add it exactly as you had it, since I have little control over how Terraform generates the file. But adding it as a yaml key at the end of each of my separate parts:

```
merge_type: 'list(append)+dict(recurse_array)+str()'
```

and this made it all work.

As far as the `#cloud-init` header... similar issue... I don't have control over how the Terraform provider generates the file. I have `#cloud-config` at the top of each of my yaml parts. Terraform I guess just generates it with the `MIME` bits up top before it, so `cloud-init schema` will always complain about `#cloud-config` not being the first line.

Any way, looks like that's fixed everything. Thank you very much!

**Comment by aciba90** [comment] 2024-07-24 06:47
Sweet! Then I am going to close this issue.

> As far as the #cloud-init header... similar issue... I don't have control over how the Terraform provider generates the file.

> The only thing is that the cloud-init schema --system --annotate will still complain about the #cloud-init not being the first line of the file.

But regarding that issue, is it possible to report that issue to the Terraform provider? Otherwise, more people will hit that warning.

**Closed by aciba90** 2024-07-24 06:47 UTC
Labels: bug, new

**Comment by hahuang65** [comment] 2024-07-24 23:25
@aciba90 I'll file with the Terraform provider maintainers.

**Comment by hahuang65** [comment] 2024-07-26 18:36
@aciba90 sorry for the delay. I filed it. I actually realized it's two issues.

First the `#cloud-init` comment not being the first line

Second, the fact that I had to add `merge_type: 'list(append)+dict(recurse_array)+str()'` to my YAML files, even though they were in my Terraform config (which I would have assumed should have done it for me):

```
  part {
    content    = file("files/user_data/parts/base.yaml")
    merge_type = "list(append)+dict(recurse_array)+str()"
  }
```
