### ISSUE TITLE
Schema validation for OpenStack metadata reports absent user-data as a schema warning incorrectly

### ISSUE THREAD

**Issue by mikalstill** [canonical/cloud-init#5803] opened 2024-10-08 20:48 UTC
# Bug report
I have been trying to get to zero warnings from cloud-init in my CI environment so I can pickup cloud errors when they occur. However, there is one error I haven't found a way to remove. This is on a Debian 12 instance.

## Steps to reproduce the problem

Boot an instance using OpenStack metadata but no user-data, which the OpenStack documentation believes is a valid configuration. You get schema warnings:

```
# grep WARNING /var/log/cloud-init.log
2024-10-07 05:53:06,468 - schema.py[WARNING]: Invalid cloud-config provided: Please run 'sudo cloud-init schema --system' to see the schema errors.
```

and

```
# cloud-init schema --system
Error:
Cloud config schema errors: format-l1.c1: File None needs to begin with "#cloud-config"
```

## Environment details
- Cloud-init version: 22.4.2 (as packaged by Debian 12)
- Operating System Distribution: Debian 12
- Cloud provider, platform or installer type: OpenStack

## cloud-init logs

See above. I'm happy to provide more detail if required, but am trying to keep the length of this report reasonable.

**Comment by TheRealFalcon** [comment] 2024-10-09 12:31
@mikalstill , this bug was fixed in 23.4 and is a duplicate of https://github.com/canonical/cloud-init/issues/4632 , so I'm going to close it as such.

**Closed by TheRealFalcon** 2024-10-09 12:31 UTC
Labels: bug, new
