### ISSUE TITLE
[enhancement(proposal/rfc)]: add support for fetching APT repo keys from remote urls 

### ISSUE THREAD

**Issue by the-wondersmith** [canonical/cloud-init#4822] opened 2024-01-30 17:04 UTC
# Enhancement

To streamline support for the [OpenPGP certificate distribution](https://wiki.debian.org/DebianRepository/UseThirdParty) model favored for newer (Debian 9+ or Ubuntu 18.04+) distros, it would be beneficial for the `apt-configure` module to support fetching of key files from remote urls (examples: [`helm`](https://helm.sh/docs/intro/install/#from-apt-debianubuntu), [`google-cloud-sdk`](https://cloud.google.com/sdk/docs/install#deb)).

# Proposal

Add `keyurl` as a supported field for `apt.sources` entries. If `keyurl` *is* present and `key`, `keyid`, and `keyserver` are *not* present in a given `source` entry, the `apt-configure` module should attempt to fetch the file pointed to by `keyurl` and if successful, populate the entry's `key` field with its contents and then simply proceed as it normally would. If unsuccessful (a non-200 response, or connection error), the error handling that would normally fire for a bad configuration entry should take over.

# Comments

While this is both an enhancement proposal as well as a request for comment, I have already implemented this feature on a local branch. I'd like feedback on the idea. Alternately if accepted the proposal is simply unobjectionable and therefore de facto accepted, I will happily submit a PR.

**Comment by holmanb** [comment] 2024-01-30 18:03
@the-wondersmith this is a duplicate of https://github.com/canonical/cloud-init/issues/4076

> Add keyurl as a supported field for apt.sources entries. If keyurl is present and key, keyid, and keyserver are not present in a given source entry, the apt-configure module should attempt to fetch the file pointed to by keyurl and if successful, populate the entry's key field with its contents and then simply proceed as it normally would. If unsuccessful (a non-200 response, or connection error), the error handling that would normally fire for a bad configuration entry should take over.

That flow makes sense. I'd like to add that the schema should accurately reflect that the keys conflict so that `cloud-init schema` commands work as expected.

I don't think anyone is working on this currently - PRs welcome :)

**Comment by holmanb** [comment] 2024-01-30 18:04
@the-wondersmith I'm going to close this issue due to the pre-existing one, please feel free to continue the conversation over there.

**Closed by holmanb** 2024-01-30 18:04 UTC
Labels: enhancement, new, duplicate
