### ISSUE TITLE
cloud-init clean command outputs wrong warning message

### ISSUE THREAD

**Issue by AliyevH** [canonical/cloud-init#4952] opened 2024-02-25 20:29 UTC
# Bug report
Warning message:
`skipping /etc/cloud/clean.d/README as its not executable or the underlying file system is mounted without executable permissions.`

## Steps to reproduce the problem
create simple file in /etc/cloud/clean.d without execution permission and run `cloud-init clean `command

## Environment details
- 23.4.3-0ubuntu0~22.04.1:
- ubuntu2204:

**Comment by AliyevH** [comment] 2024-02-25 20:33
Tried to search sorce code.
Here is a function to check if file is executable. all other cases commands shows warning.
what about to add aditional check to see if it is simple file or not?
Because this message a little confuses when there is a simple file.

```
if is_exe(exe_path):
    ....
else:
    LOG.warning....
```

**Comment by TheRealFalcon** [comment] 2024-02-26 14:29
Thanks @AliyevH . This is a duplicate of https://github.com/canonical/cloud-init/issues/4760 and will be fixed in 24.1.

**Closed by TheRealFalcon** 2024-02-26 14:29 UTC
Labels: bug, new
