### ISSUE TITLE
Ubuntu : VMware extra_config guestinfo.userdata not used after switching from 22.04.1 to 22.04.2 or later

### ISSUE THREAD

**Issue by erSitzt** [canonical/cloud-init#4977] opened 2024-02-28 17:35 UTC
# Bug report

I'm using Packer to create a VMware template, which is later deployed using terraform.
This is/was working fine until i updated the base-iso for the packer template to 22.04.2 or higher.
During the packer template build i run `apt-get dist-upgrade` and using either base iso i end up with an up to date ubuntu template.
Terraform uses `extra_config` with `guestinfo.userdata` and `guestinfo.metadata`  to make minimal changes like network config, ssh pubkey for a user and installing some packages.

extra_config from terraform config:
```
  extra_config = {
    "guestinfo.metadata" = base64encode(templatefile("${path.module}/templates/metadata.yml.tpl", {
      node_ip       = "${var.vm_server_network}${count.index +  var.vm_server_startip}/${var.vm_server_netmask}",
      node_gateway  = var.vm_server_gateway,
      node_dns      = var.vm_dns,
      node_hostname = "${var.vm_server_prefix}${count.index + 1}"
    }))

    "guestinfo.metadata.encoding" = "base64"

    "guestinfo.userdata" = base64encode(templatefile("${path.module}/templates/userdata.yml.tpl", {
      vm_ssh_user = var.vm_ssh_user,
      vm_ssh_key = var.vm_ssh_key
    }))
    "guestinfo.userdata.encoding" = "base64"
  }
```

metadata:
```
network:
  version: 2
  ethernets:
    ens192:
      dhcp4: false
      addresses:
        - ${node_ip}
      gateway4: ${node_gateway}
      nameservers:
        addresses:
          - ${node_dns}
local-hostname: ${node_hostname}
instance-id: ${node_hostname}
```
userdata:
```
#cloud-config
users:
  - name: ${vm_ssh_user}
    ssh-authorized-keys:
      - ${vm_ssh_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
runcmd:
  - sudo apt-get remove -y docker docker-engine docker.io containerd runc
  - sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release open-iscsi nfs-common
```
nothing special..

as soon as i switch to the newer ubuntu iso, both are no longer used to configure the VM.
Packer and Terraform scripts remain unchanged.

I can see the userdata/metadata in the VMs config and i can query it with 
```
vmware-rpctool "info-get guestinfo.metadata" | base64 -d
vmware-rpctool "info-get guestinfo.userdata" | base64 -d
```

## Steps to reproduce the problem
Not sure yet.. i'll try to set up a barebones packer/terraform or try it with the examples projects to see if i can reproduce.

## Environment details
- Cloud-init version:
`/usr/bin/cloud-init 23.4.3-0ubuntu0~22.04.1` in both instances
- Operating System Distribution:
Ubuntu 22.04.1 working ( base iso version.. updated to 22.04.4 during template build )
Uubntu 22.04.2+ not working ( base iso version.. all updated to 22.04.4 in the template build process )

- Cloud provider, platform or installer type:

## cloud-init logs
Will attach after i have rerun with both base isos.

**Comment by erSitzt** [comment] 2024-02-28 18:10
Before i attach the full logs.. first difference is this

The template with the problem logs this
```
Looking for data source in: ['nocloud-net', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
```

and the template that works looks like this
```
Looking for data source in: ['VMware'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
```

The bottom one is what i would expect from the cleanup script that i run at the end of the packer template build
```
# optional: cleaning cloud-init
echo '> Cleaning cloud-init'
rm -rf /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
rm -rf /etc/cloud/cloud.cfg.d/99-installer.cfg
rm -rf /etc/cloud/clean.d/README
#echo 'datasource_list: [ VMware, NoCloud, ConfigDrive ]' | tee /etc/cloud/cloud.cfg.d/90_dpkg.cfg
echo "disable_vmware_customization: false" >> /etc/cloud/cloud.cfg
echo 'datasource_list: [ VMware ]' | tee /etc/cloud/cloud.cfg.d/90_dpkg.cfg
/usr/bin/cloud-init clean --logs
```

**Comment by holmanb** [comment] 2024-02-28 18:56
> Before i attach the full logs..

Please do, that will help much in diagnosing your issue. Both `/var/log/cloud-init/cloud-init.log` and `/run/cloud-init/ds-identify.log` will be important.

**Comment by erSitzt** [comment] 2024-02-28 19:12
[cloud-init.tar.gz](https://github.com/canonical/cloud-init/files/14438999/cloud-init.tar.gz)
[cloud-init_not_working.tar.gz](https://github.com/canonical/cloud-init/files/14439002/cloud-init_not_working.tar.gz)

**Comment by erSitzt** [comment] 2024-02-28 19:16
working `ds-identify.log`

```
❯ cat run/cloud-init/ds-identify.log                                                                                                                                                                                                        
[up 2.96s] ds-identify
policy loaded: mode=enabled report=false found=all maybe=all notfound=disabled
DMI_PRODUCT_NAME=VMware Virtual Platform
DMI_SYS_VENDOR=VMware, Inc.
DMI_PRODUCT_SERIAL=VMware-42 21 7c b6 6d 5a 4d 36-53 d0 0e cb 2a a2 11 40
DMI_PRODUCT_UUID=b67c2142-5a6d-364d-53d0-0ecb2aa21140
PID_1_PRODUCT_NAME=unavailable
DMI_CHASSIS_ASSET_TAG=No Asset Tag
DMI_BOARD_NAME=440BX Desktop Reference Platform
FS_LABELS=
ISO9660_DEVS=
KERNEL_CMDLINE=BOOT_IMAGE=/boot/vmlinuz-5.15.0-97-generic root=UUID=f614b320-03b0-4ba9-9ff8-c719c6d731a1 ro autoinstall ds=nocloud-net
VIRT=vmware
UNAME_KERNEL_NAME=Linux
UNAME_KERNEL_RELEASE=5.15.0-97-generic
UNAME_KERNEL_VERSION=#107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024
UNAME_MACHINE=x86_64
UNAME_NODENAME=localhost
UNAME_OPERATING_SYSTEM=GNU/Linux
DSNAME=nocloud-net
DSLIST=nocloud-net
MODE=enabled
ON_FOUND=all
ON_MAYBE=all
ON_NOTFOUND=disabled
pid=398 ppid=378
is_container=false
mode=enabled. returning 0
[up 3.00s] returning 0
[up 24.04s] ds-identify
policy loaded: mode=enabled report=false found=all maybe=all notfound=disabled
DMI_PRODUCT_NAME=VMware Virtual Platform
DMI_SYS_VENDOR=VMware, Inc.
DMI_PRODUCT_SERIAL=VMware-42 21 7c b6 6d 5a 4d 36-53 d0 0e cb 2a a2 11 40
DMI_PRODUCT_UUID=b67c2142-5a6d-364d-53d0-0ecb2aa21140
PID_1_PRODUCT_NAME=unavailable
DMI_CHASSIS_ASSET_TAG=No Asset Tag
DMI_BOARD_NAME=440BX Desktop Reference Platform
FS_LABELS=
ISO9660_DEVS=
KERNEL_CMDLINE=BOOT_IMAGE=/boot/vmlinuz-5.15.0-97-generic root=UUID=f614b320-03b0-4ba9-9ff8-c719c6d731a1 ro autoinstall ds=nocloud-net
VIRT=vmware
UNAME_KERNEL_NAME=Linux
UNAME_KERNEL_RELEASE=5.15.0-97-generic
UNAME_KERNEL_VERSION=#107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024
UNAME_MACHINE=x86_64
UNAME_NODENAME=rke2-zentrale-dev-server-1
UNAME_OPERATING_SYSTEM=GNU/Linux
DSNAME=nocloud-net
DSLIST=nocloud-net
MODE=enabled
ON_FOUND=all
ON_MAYBE=all
ON_NOTFOUND=disabled
pid=1497 ppid=1492
is_container=false
mode=enabled. returning 0
[up 24.07s] returning 0
[up 24.31s] ds-identify
policy loaded: mode=enabled report=false found=all maybe=all notfound=disabled
DMI_PRODUCT_NAME=VMware Virtual Platform
DMI_SYS_VENDOR=VMware, Inc.
DMI_PRODUCT_SERIAL=VMware-42 21 7c b6 6d 5a 4d 36-53 d0 0e cb 2a a2 11 40
DMI_PRODUCT_UUID=b67c2142-5a6d-364d-53d0-0ecb2aa21140
PID_1_PRODUCT_NAME=unavailable
DMI_CHASSIS_ASSET_TAG=No Asset Tag
DMI_BOARD_NAME=440BX Desktop Reference Platform
FS_LABELS=
ISO9660_DEVS=
KERNEL_CMDLINE=BOOT_IMAGE=/boot/vmlinuz-5.15.0-97-generic root=UUID=f614b320-03b0-4ba9-9ff8-c719c6d731a1 ro autoinstall ds=nocloud-net
VIRT=vmware
UNAME_KERNEL_NAME=Linux
UNAME_KERNEL_RELEASE=5.15.0-97-generic
UNAME_KERNEL_VERSION=#107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024
UNAME_MACHINE=x86_64
UNAME_NODENAME=rke2-zentrale-dev-server-1
UNAME_OPERATING_SYSTEM=GNU/Linux
DSNAME=nocloud-net
DSLIST=nocloud-net
MODE=enabled
ON_FOUND=all
ON_MAYBE=all
ON_NOTFOUND=disabled
pid=1541 ppid=1533
is_container=false
mode=enabled. returning 0
[up 24.33s] returning 0
[up 24.53s] ds-identify
policy loaded: mode=enabled report=false found=all maybe=all notfound=disabled
DMI_PRODUCT_NAME=VMware Virtual Platform
DMI_SYS_VENDOR=VMware, Inc.
DMI_PRODUCT_SERIAL=VMware-42 21 7c b6 6d 5a 4d 36-53 d0 0e cb 2a a2 11 40
DMI_PRODUCT_UUID=b67c2142-5a6d-364d-53d0-0ecb2aa21140
PID_1_PRODUCT_NAME=unavailable
DMI_CHASSIS_ASSET_TAG=No Asset Tag
DMI_BOARD_NAME=440BX Desktop Reference Platform
FS_LABELS=
ISO9660_DEVS=
KERNEL_CMDLINE=BOOT_IMAGE=/boot/vmlinuz-5.15.0-97-generic root=UUID=f614b320-03b0-4ba9-9ff8-c719c6d731a1 ro autoinstall ds=nocloud-net
VIRT=vmware
UNAME_KERNEL_NAME=Linux
UNAME_KERNEL_RELEASE=5.15.0-97-generic
UNAME_KERNEL_VERSION=#107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024
UNAME_MACHINE=x86_64
UNAME_NODENAME=rke2-zentrale-dev-server-1
UNAME_OPERATING_SYSTEM=GNU/Linux
DSNAME=nocloud-net
DSLIST=nocloud-net
MODE=enabled
ON_FOUND=all
ON_MAYBE=all
ON_NOTFOUND=disabled
pid=1591 ppid=1584
is_container=false
mode=enabled. returning 0
[up 24.55s] returning 0
[up 24.67s] ds-identify
policy loaded: mode=enabled report=false found=all maybe=all notfound=disabled
DMI_PRODUCT_NAME=VMware Virtual Platform
DMI_SYS_VENDOR=VMware, Inc.
DMI_PRODUCT_SERIAL=VMware-42 21 7c b6 6d 5a 4d 36-53 d0 0e cb 2a a2 11 40
DMI_PRODUCT_UUID=b67c2142-5a6d-364d-53d0-0ecb2aa21140
PID_1_PRODUCT_NAME=unavailable
DMI_CHASSIS_ASSET_TAG=No Asset Tag
DMI_BOARD_NAME=440BX Desktop Reference Platform
FS_LABELS=
ISO9660_DEVS=
KERNEL_CMDLINE=BOOT_IMAGE=/boot/vmlinuz-5.15.0-97-generic root=UUID=f614b320-03b0-4ba9-9ff8-c719c6d731a1 ro autoinstall ds=nocloud-net
VIRT=vmware
UNAME_KERNEL_NAME=Linux
UNAME_KERNEL_RELEASE=5.15.0-97-generic
UNAME_KERNEL_VERSION=#107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024
UNAME_MACHINE=x86_64
UNAME_NODENAME=rke2-zentrale-dev-server-1
UNAME_OPERATING_SYSTEM=GNU/Linux
DSNAME=nocloud-net
DSLIST=nocloud-net
MODE=enabled
ON_FOUND=all
ON_MAYBE=all
ON_NOTFOUND=disabled
pid=1623 ppid=1617
is_container=false
mode=enabled. returning 0
[up 24.70s] returning 0
[up 25.32s] ds-identify
policy loaded: mode=enabled report=false found=all maybe=all notfound=disabled
DMI_PRODUCT_NAME=VMware Virtual Platform
DMI_SYS_VENDOR=VMware, Inc.
DMI_PRODUCT_SERIAL=VMware-42 21 7c b6 6d 5a 4d 36-53 d0 0e cb 2a a2 11 40
DMI_PRODUCT_UUID=b67c2142-5a6d-364d-53d0-0ecb2aa21140
PID_1_PRODUCT_NAME=unavailable
DMI_CHASSIS_ASSET_TAG=No Asset Tag
DMI_BOARD_NAME=440BX Desktop Reference Platform
FS_LABELS=
ISO9660_DEVS=
KERNEL_CMDLINE=BOOT_IMAGE=/boot/vmlinuz-5.15.0-97-generic root=UUID=f614b320-03b0-4ba9-9ff8-c719c6d731a1 ro autoinstall ds=nocloud-net
VIRT=vmware
UNAME_KERNEL_NAME=Linux
UNAME_KERNEL_RELEASE=5.15.0-97-generic
UNAME_KERNEL_VERSION=#107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024
UNAME_MACHINE=x86_64
UNAME_NODENAME=rke2-zentrale-dev-server-1
UNAME_OPERATING_SYSTEM=GNU/Linux
DSNAME=nocloud-net
DSLIST=nocloud-net
MODE=enabled
ON_FOUND=all
ON_MAYBE=all
ON_NOTFOUND=disabled
pid=1962 ppid=1956
is_container=false
mode=enabled. returning 0
[up 25.34s] returning 0
[up 25.54s] ds-identify
policy loaded: mode=enabled report=false found=all maybe=all notfound=disabled
DMI_PRODUCT_NAME=VMware Virtual Platform
DMI_SYS_VENDOR=VMware, Inc.
DMI_PRODUCT_SERIAL=VMware-42 21 7c b6 6d 5a 4d 36-53 d0 0e cb 2a a2 11 40
DMI_PRODUCT_UUID=b67c2142-5a6d-364d-53d0-0ecb2aa21140
PID_1_PRODUCT_NAME=unavailable
DMI_CHASSIS_ASSET_TAG=No Asset Tag
DMI_BOARD_NAME=440BX Desktop Reference Platform
FS_LABELS=
ISO9660_DEVS=
KERNEL_CMDLINE=BOOT_IMAGE=/boot/vmlinuz-5.15.0-97-generic root=UUID=f614b320-03b0-4ba9-9ff8-c719c6d731a1 ro autoinstall ds=nocloud-net
VIRT=vmware
UNAME_KERNEL_NAME=Linux
UNAME_KERNEL_RELEASE=5.15.0-97-generic
UNAME_KERNEL_VERSION=#107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024
UNAME_MACHINE=x86_64
UNAME_NODENAME=rke2-zentrale-dev-server-1
UNAME_OPERATING_SYSTEM=GNU/Linux
DSNAME=nocloud-net
DSLIST=nocloud-net
MODE=enabled
ON_FOUND=all
ON_MAYBE=all
ON_NOTFOUND=disabled
pid=2004 ppid=1997
is_container=false
mode=enabled. returning 0
[up 25.57s] returning 0
[up 25.71s] ds-identify
policy loaded: mode=enabled report=false found=all maybe=all notfound=disabled
DMI_PRODUCT_NAME=VMware Virtual Platform
DMI_SYS_VENDOR=VMware, Inc.
DMI_PRODUCT_SERIAL=VMware-42 21 7c b6 6d 5a 4d 36-53 d0 0e cb 2a a2 11 40
DMI_PRODUCT_UUID=b67c2142-5a6d-364d-53d0-0ecb2aa21140
PID_1_PRODUCT_NAME=unavailable
DMI_CHASSIS_ASSET_TAG=No Asset Tag
DMI_BOARD_NAME=440BX Desktop Reference Platform
FS_LABELS=
ISO9660_DEVS=
KERNEL_CMDLINE=BOOT_IMAGE=/boot/vmlinuz-5.15.0-97-generic root=UUID=f614b320-03b0-4ba9-9ff8-c719c6d731a1 ro autoinstall ds=nocloud-net
VIRT=vmware
UNAME_KERNEL_NAME=Linux
UNAME_KERNEL_RELEASE=5.15.0-97-generic
UNAME_KERNEL_VERSION=#107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024
UNAME_MACHINE=x86_64
UNAME_NODENAME=rke2-zentrale-dev-server-1
UNAME_OPERATING_SYSTEM=GNU/Linux
DSNAME=nocloud-net
DSLIST=nocloud-net
MODE=enabled
ON_FOUND=all
ON_MAYBE=all
ON_NOTFOUND=disabled
pid=2036 ppid=2030
is_container=false
mode=enabled. returning 0
[up 25.72s] returning 0
```

**Comment by dermotbradley** [comment] 2024-02-28 20:13
@erSitzt the "metadata" you showed looks like a combined meta-data (the last 2 lines) and network-config contents.

I'm not sure if this is valid.

**Comment by erSitzt** [comment] 2024-02-28 20:24
@dermotbradley 
If this is not valid, shouln't it fail after detecting that there is a VMware datasource with userdata/metadata ?
Both are base64 encoded and would have to be "detected" and decoded before anything could fail with incorrect schema/syntax
And if it is not valid, why would it work when starting off with a slightly older ubuntu iso ?

I have deployed 20-30 vm with the identical setup, it only broke when using a newer iso for creating the template.

**Comment by dermotbradley** [comment] 2024-02-28 20:37
> @dermotbradley If this is not valid, shouln't it fail after detecting that there is a VMware datasource with userdata/metadata ?

I'm not familiar with the VMware datasource so I was making a more general comment. However from looking at the [VMware-specific docs](https://cloudinit.readthedocs.io/en/latest/reference/datasources/vmware.html#configuring-the-network) it does appear that this network-config is embedded within meta-data - my mistake.

**Comment by erSitzt** [comment] 2024-02-29 18:19
So when creating the template with packer, packer boot the the iso by typing a boot_cmd with these options
`"linux /casper/vmlinuz --- autoinstall ds=\"nocloud-net;seedfrom=http://{{ .HTTPIP }}:{{ .HTTPPort }}/\"",`

These remain, not sure why, as the default options in `/boot/grub/grub.cfg`. `ds-identify` always returns this datasource when checking `DI_KERNEL_CMDLINE`
When i remove these parameters, cloud-init works on reboot as intended...  and i dont understand why starting from an older ubuntu iso works, even though the parameters are the same and still present in all deployed VMs from last year...

I'm confused :)

**Comment by holmanb** [comment] 2024-03-06 01:24
> /usr/bin/cloud-init 23.4.3-0ubuntu0~22.04.1 in both instances

I suspect that something external to cloud-init is trying to modify ds-identify's behavior in the 22.04.1 case, but behaves differently in the 22.04.2 case.

In the "not working" case, ds-identify appears to be in the default mode ("search")

In the "working" case, ds-identify is in "enabled" mode. Something has set a custom policy for ds-identify. As far as I can tell, there are two ways to do this: 1) the kernel command line 2) /etc/cloud/ds-identify.cfg. Since the kernel is printed and doesn't have a policy, I would assume that you have a `/etc/cloud/ds-identify.cfg` in the working case and don't have one in the non-working case.

> Not sure why its repeating in this one ?

I don't know, but if I had to guess I would assume that in "enabled" mode, ds-identify result doesn't get cached. `systemctl daemon-reload` reruns all generators, which is probably where the extra logs come from.

@erSitzt I think that this is probably a subiquity question. I'm guessing that [this line](https://github.com/canonical/subiquity/blob/2fd9c68571394c4dcc7ddde07c61306a4e34e27a/subiquity/models/subiquity.py#L434) is where the config is coming from. In both cases, cloud-init appears to be working as expected, so I am going to close this issue.

**Comment by erSitzt** [comment] 2024-03-06 08:48
Thanks @holmanb i'm not sure about the different modes.. i can remove the kernel cmd parameter at any point in an already deployed vm and cloud-init will work. so no difference in any other files, just change grub config and reboot. 

I just tried the current `ds-identify` from this repo on a system installed with ubuntu 22.04.1 and updated to 22.04.2 and these are the results

```
root@rke2-zentrale-infra-agent-1:/tmp# DEBUG_LEVEL=2 DI_LOG=stderr /usr/lib/cloud-init/ds-identify --force
[up 15640107.99s] ds-identify --force
policy loaded: mode=enabled report=false found=all maybe=all notfound=disabled
/etc/cloud/cloud.cfg.d/90_dpkg.cfg set datasource_list: [ VMware, NoCloud, ConfigDrive ]
DMI_PRODUCT_NAME=VMware Virtual Platform
DMI_SYS_VENDOR=VMware, Inc.
DMI_PRODUCT_SERIAL=VMware-42 21 de 28 b7 d6 76 25-ea ad 43 3c 7c e4 45 ec
DMI_PRODUCT_UUID=28de2142-d6b7-2576-eaad-433c7ce445ec
PID_1_PRODUCT_NAME=unavailable
DMI_CHASSIS_ASSET_TAG=No Asset Tag
DMI_BOARD_NAME=440BX Desktop Reference Platform
FS_LABELS=
ISO9660_DEVS=
KERNEL_CMDLINE=BOOT_IMAGE=/boot/vmlinuz-5.15.0-83-generic root=UUID=ae1a67c6-1a23-4bae-ae59-66225df16e75 ro autoinstall ds=nocloud-net
VIRT=vmware
UNAME_KERNEL_NAME=Linux
UNAME_KERNEL_RELEASE=5.15.0-83-generic
UNAME_KERNEL_VERSION=#92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023
UNAME_MACHINE=x86_64
UNAME_NODENAME=rke2-zentrale-infra-agent-1
UNAME_OPERATING_SYSTEM=GNU/Linux
DSNAME=
DSLIST=VMware NoCloud ConfigDrive
MODE=enabled
ON_FOUND=all
ON_MAYBE=all
ON_NOTFOUND=disabled
pid=3825646 ppid=3794638
is_container=false
mode=enabled. returning 0
[up 15640108.01s] returning 0
```

and with the version from this repo

```
root@rke2-zentrale-infra-agent-1:/tmp# DEBUG_LEVEL=2 DI_LOG=stderr ./dsidentify_neu --force
[up 15640180.28s] ds-identify --force
detected vmware via ds-identify
policy loaded: mode=enabled report=false found=all maybe=all notfound=disabled
DMI_PRODUCT_NAME=VMware Virtual Platform
DMI_SYS_VENDOR=VMware, Inc.
DMI_PRODUCT_SERIAL=VMware-42 21 de 28 b7 d6 76 25-ea ad 43 3c 7c e4 45 ec
DMI_PRODUCT_UUID=28de2142-d6b7-2576-eaad-433c7ce445ec
PID_1_PRODUCT_NAME=unavailable
DMI_CHASSIS_ASSET_TAG=No Asset Tag
DMI_BOARD_NAME=440BX Desktop Reference Platform
FS_LABELS=
ISO9660_DEVS=
KERNEL_CMDLINE=BOOT_IMAGE=/boot/vmlinuz-5.15.0-83-generic root=UUID=ae1a67c6-1a23-4bae-ae59-66225df16e75 ro autoinstall ds=nocloud-net
VIRT=vmware
UNAME_KERNEL_NAME=Linux
UNAME_KERNEL_VERSION=#92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023
UNAME_MACHINE=x86_64
DSNAME=nocloud-net
DSLIST=nocloud-net
MODE=enabled
ON_FOUND=all
ON_MAYBE=all
ON_NOTFOUND=disabled
pid=3827597 ppid=3794638
is_container=false
mode=enabled. returning 0
[up 15640180.32s] returning 0
```

It looks like there is a change in `ds-identify` that causes this.
This was the version in my test which works
https://github.com/canonical/cloud-init/commits/ubuntu/23.1.2-0ubuntu0_22.04.1/tools/ds-identify

Updating and rerunning it on the same vm
`Entpacken von cloud-init (23.4.4-0ubuntu0~22.04.1) über (23.1.2-0ubuntu0~22.04.1) ...`
And it fails too

```
root@rke2-zentrale-infra-agent-1:/tmp# DEBUG_LEVEL=2 DI_LOG=stderr /usr/lib/cloud-init/ds-identify --force
[up 15641415.80s] ds-identify --force
policy loaded: mode=enabled report=false found=all maybe=all notfound=disabled
DMI_PRODUCT_NAME=VMware Virtual Platform
DMI_SYS_VENDOR=VMware, Inc.
DMI_PRODUCT_SERIAL=VMware-42 21 de 28 b7 d6 76 25-ea ad 43 3c 7c e4 45 ec
DMI_PRODUCT_UUID=28de2142-d6b7-2576-eaad-433c7ce445ec
PID_1_PRODUCT_NAME=unavailable
DMI_CHASSIS_ASSET_TAG=No Asset Tag
DMI_BOARD_NAME=440BX Desktop Reference Platform
FS_LABELS=
ISO9660_DEVS=
KERNEL_CMDLINE=BOOT_IMAGE=/boot/vmlinuz-5.15.0-83-generic root=UUID=ae1a67c6-1a23-4bae-ae59-66225df16e75 ro autoinstall ds=nocloud-net
VIRT=vmware
UNAME_KERNEL_NAME=Linux
UNAME_KERNEL_RELEASE=5.15.0-83-generic
UNAME_KERNEL_VERSION=#92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023
UNAME_MACHINE=x86_64
UNAME_NODENAME=rke2-zentrale-infra-agent-1
UNAME_OPERATING_SYSTEM=GNU/Linux
DSNAME=nocloud-net
DSLIST=nocloud-net
MODE=enabled
ON_FOUND=all
ON_MAYBE=all
ON_NOTFOUND=disabled
pid=3861696 ppid=3794638
is_container=false
mode=enabled. returning 0
[up 15641415.82s] returning 0
```

**Comment by erSitzt** [comment] 2024-03-06 08:52
I think there was a change somewhere that skips everything else if a kernel option with a datasource is found... i'm very bad at shell scripting syntax, so im not totally sure...

Regarding everything i read, if this is desired behaviour, it is not that clearly stated anywhere... or i didnt find it

**Comment by holmanb** [comment] 2024-03-06 16:23
> Thanks @holmanb i'm not sure about the different modes.. i can remove the kernel cmd parameter at any point in an already deployed vm and cloud-init will work. 

In "search" mode, I would expect that removing the kernel override causes ds-identify to find your preferred datasource. Ds-identify exists to identify the datasource. The "enabled" mode merely overrides this searching (and therefore ignores the kernel commandline). Kernel commandline is just treated as an override for searching, in the same way that a single configured datasource in the `datasource_list` is treated as an override.

> so no difference in any other files, just change grub config and reboot.

You said before that you see both the failure and non-failure paths with `23.4.3-0ubuntu0~22.04.1`, that the difference is how you get to that version. That tells me that it is an environmental issue that some sort of environmental issue is causing this change in behavior - not a change in cloud-init.

> And it fails too

Can you please clarify what you consider the failure path? From your previous comments I had come to the conclusion that what you considered a failure was ds-identify writing out the `/run/cloud/cloud.cfg` file containing: 
```
datasource_list: [ nocloud-net, None ]
```

This is what causes the following log:
```
Looking for data source in: ['nocloud-net', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
```

However in the three latest ds-identify logs, I see the following:
```
mode=enabled. returning 0
```

Which implies that no `/run/cloud/cloud.cfg` was written, which means that cloud-init should have been force enabled and would use either the `datasource_list` in `/etc/cloud/cloud.cfg.d/*.cfg`, or the `datasource_list` in `/etc/cloud/cloud.cfg`, or if neither of those have a `datasource_list` defined, then it would iterate over all of the datasources until it finds one that is viable.

I can see that in one of your logs above, something defined the datasource_list as expected:
```
/etc/cloud/cloud.cfg.d/90_dpkg.cfg set datasource_list: [ VMware, NoCloud, ConfigDrive ]
```

> Regarding everything i read, if this is desired behaviour, it is not that clearly stated anywhere... or i didnt find it

This is all very under-documented. We don't typically expect users to have to deal with these configurations.

**Comment by holmanb** [comment] 2024-03-06 16:46
@erSitzt I just want to follow up and make sure that you're aware that you're filling a bug against cloud-init, but you are using Subiquity. This being expected behavior is from a cloud-init perspective - there are ways in which Subiquity uses cloud-init that I do not understand, and you will probably have better success going through [Subiquity's support channels](https://cloudinit.readthedocs.io/en/latest/reference/faq.html#autoinstall-preruncmd-postruncmd). My guess is that you're having some issue with providing subiquity the correct configuration, but I really do not know. Cloud-init gets used by Subiquity in multiple stages, but I don't fully understand how it does and you'll probably get better advice from a Subiquity developer.

Best of luck.

**Comment by erSitzt** [comment] 2024-03-06 16:55
Sorry, but no :)

Packer builds a template from an ubuntu iso, using the autoinstall feature ( with a config, seeded from a local http-server, that looks like cloud-init, but is used by subiquity... i didnt know that at first, why is was confused)

The second step is a deployment of the vmware template using terraform, which provides the userdata, and this is used by cloud-init, not subiquity.

And as i stated, the ONLY change necessary to change the behavior, was trying a newer version of ds-identify instead of the one installed by apt.

 It should be easy to verify this behavior.
Set a kernel parameter of `ds=\"nocloud-net` and see if any other configured datasource is still used.

**Comment by erSitzt** [comment] 2024-03-06 17:15
Hmm i think we were somehow talking past each other...

@holmanb 
I can see that you did the changes for the kernel cmdline handling to override the datasource and disable search.
I guess you didn't see the `ds=nocloud.net` when i first posted the kernel commandline config.

And i guess  made a mistake when initially checking the cloud-init versions installed on my servers. Probably one was the older version shipped with 22.04.1

**Comment by holmanb** [comment] 2024-03-06 18:23
> Set a kernel parameter of ds=\"nocloud-net and see if any other configured datasource is still used

To make sure that I understand your expectations: are you saying that on version `23.1.2-0ubuntu0_22.04.1`, this does not cause ds-identify to identify nocloud-net as the datasource, but that on `23.4.3-0ubuntu0~22.04.1`, it identifies nocloud-net which breaks your workflow on VMware?

**Comment by holmanb** [comment] 2024-03-06 18:35
@erSitzt can you please link to the two isos you are using?

**Comment by holmanb** [comment] 2024-03-06 19:37
Cloud-init on Ubuntu is expected to not change behavior across stable release updates for the same series. This change in behavior is relatively small, and it was released almost a year without any bug reports yet. I think we will probably get out a fix in the next release cycle.

@erSitzt for now I would recommend using the following config with 23.2+. It looks like that is what worked for you in 23.1, and it should continue to work in 23.2+. 
```
$ cat /etc/cloud/cloud.cfg.d/90_dpkg.cfg
[ VMware, NoCloud, ConfigDrive ]
$ cat /etc/cloud/ds-identify.cfg
policy: enabled
$
```

note: The `NoCloud` entry probably isn't even required, but shouldn't hurt anything as long as you are on VMware - and since I still don't believe that I have all of the details about how you're using cloud-init, I'm not going to recommend against including it.

**Comment by erSitzt** [comment] 2024-03-06 19:41
@holmanb is was using these two isos
```
#  -var='os_iso_checksum=10f19c5b2b8d6db711582e0e27f5116296c34fe4b313ba45f9b201a5007056cb' \
#  -var='os_iso_url=https://old-releases.ubuntu.com/releases/22.04.1/ubuntu-22.04.1-live-server-amd64.iso' \

#  -var='os_iso_checksum=5e38b55d57d94ff029719342357325ed3bda38fa80054f9330dc789cd2d43931' \
#  -var='os_iso_url=https://old-releases.ubuntu.com/releases/22.04.2/ubuntu-22.04.2-live-server-amd64.iso' \
```

First i thought this might be happening because of leftover stuff from the packer build, but after i could get it working in several deployed VMs by just removing the kernel cmd this looked more like a change in behavior.

This is my cleanup stuff related to cloud-init
```
sed -i 's|nocloud-net;seedfrom=http://.*/|vmware|' /etc/default/grub
update-grub


# optional: cleaning cloud-init
echo '> Cleaning cloud-init'
rm -rf /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
rm -rf /etc/cloud/cloud.cfg.d/99-installer.cfg
rm -rf /etc/cloud/clean.d/README
#echo 'datasource_list: [ VMware, NoCloud, ConfigDrive ]' | tee /etc/cloud/cloud.cfg.d/90_dpkg.cfg
echo "disable_vmware_customization: false" >> /etc/cloud/cloud.cfg
echo 'datasource_list: [ VMware ]' | tee /etc/cloud/cloud.cfg.d/90_dpkg.cfg
/usr/bin/cloud-init clean --logs --machine-id

```

and my `ds-identify.cfg` already looks like you posted

**Comment by holmanb** [comment] 2024-03-06 20:37
@erSitzt Thanks for this bug report. I'm glad that you've found a workaround.

We use Github for tracking upstream bugs and Launchpad to track downstream ubuntu bugs, so I am going to close this issue. I just filed this as a [downstream bug here](https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2056367).

**Closed by holmanb** 2024-03-06 20:37 UTC
Labels: bug, breaking change

**Comment by erSitzt** [comment] 2024-03-11 08:49
@holmanb 

Just for reference and completeness here

This is why the "unnecessary" stuff from the packer boot_command ends up in the installed servers /etc/default/grub

https://bugs.launchpad.net/subiquity/+bug/1956452

**Comment by holmanb** [comment] 2024-03-11 16:04
> This is why the "unnecessary" stuff from the packer boot_command ends up in the installed servers /etc/default/grub

Interesting, thanks for following up!
