### ISSUE TITLE
cloud-init status --wait hangs forever if bootcmd fails

### ISSUE THREAD

**Issue by pieter-lautus** [canonical/cloud-init#4505] opened 2023-10-12 06:23 UTC
# Bug report
When a bootcmd fails, `cloud-init status --long` reports status `running` instead of `error`. Likely for this reason, `cloud-init status --wait` will hang indefinitely, instead of exiting with an error code.

## Steps to reproduce the problem
We discovered this bug in the context of an LXD container, but that is likely irrelevant to the issue at hand.

1. Run:
```
lxc launch images:ubuntu/20.04 foo
lxc shell foo
apt install cloud-init
```
2. Create `/etc/cloud/cloud.cfg.d/99_broken.cfg` with the following contents:
```
bootcmd:
- exit 1
```
3. Run `systemctl restart cloud-init`. It will fail, as expected.
4. Run `cloud-init status --long`. You will see something like:
  ```
  status: running
  boot_status_code: enabled-by-generator
  last_update: Thu, 12 Oct 2023 05:57:39 +0000
  detail:
  ('bootcmd', ProcessExecutionError("Unexpected error while running command.\nCommand: ['/bin/sh', '/run/cloud-init/tmp/tmpec2a_i74.sh']\nExit code: 1\nReason: -\nStdout: -\nStderr: -"))
  ```
  The status `running` looks wrong.
5. Run `cloud-init status --wait`. It will run indefinitely, which is wrong.
6. Run `apt install cloud-init=20.1-10-g71af48df-0ubuntu5`
7. Run `systemctl restart cloud-init`. It will fail, as expected.
8. Run `cloud-init status --long --wait`. It will immediately fail, as expected, with the expected output:
```
status: error
time: Thu, 12 Oct 2023 06:00:29 +0000
detail:
('bootcmd', ProcessExecutionError("Unexpected error while running command.\nCommand: ['/bin/sh', '/run/cloud-init/tmp/tmp0n300745.sh']\nExit code: 1\nReason: -\nStdout: -\nStderr: -"))
```

## Environment details
- Cloud-init version: 23.3.1-0ubuntu1~20.04.1
- Operating System Distribution: Ubuntu 20.04 LXD image from https://cloud-images.ubuntu.com/releases
- Cloud provider, platform or installer type: LXD

## cloud-init logs
[cloud-init.tar.gz](https://github.com/canonical/cloud-init/files/12877890/cloud-init.tar.gz)

**Comment by holmanb** [comment] 2023-10-12 15:47
Thanks for the report @pieter-lautus.

> apt install cloud-init

Why not just use a cloud image? Is there some reason you don't want cloud-init already installed?

> Run systemctl restart cloud-init. It will fail, as expected.

What are you trying to accomplish with this command?

If you were attempting to "run cloud-init", I'd suggest `cloud-init clean --logs --reboot` - or just reboot the system since you are manually installing cloud-init. In theory you could force the other services to run manually, but this isn't the expected way to use cloud-init and unsupported, so I'd have to ask "why", because I assume there is a better way (just as I ask why you manually restart service 2 out of 4 and then expect `cloud-init status --wait` to finish).

Cloud-init exists as four separate services, this command will force the first two to run (note that the logs only report "init-local" and "init" stages as run), which leaves cloud-init unfinished (i.e, "running", as far as `cloud-init status` is concerned). Two more services must run before cloud-init is considered "done", and the way you are trying to run cloud-init will not force these to run.

Typically cloud-init is pre-installed in cloud images, and will run "out of the box" with the provided cloud config. I'd suggest [reviewing the LXD tutorial](https://cloudinit.readthedocs.io/en/latest/tutorial/index.html) for a more convenient (and expected) way to use cloud-init with LXD images.

**Comment by pieter-lautus** [comment] 2023-10-17 05:07
Hi @holmanb 

> Why not just use a cloud image? Is there some reason you don't want cloud-init already installed?

My bug report is a distillation of unit tests surrounding the process we use to build our own images. Currently, we start with an Ubuntu 20.04 LXD image from https://cloud-images.ubuntu.com/releases and install cloud-init etc. ourselves. We have not yet tried to retarget our system on top of a more cloud-friendly base image, since our system is quite monolothic.

> > Run systemctl restart cloud-init. It will fail, as expected.
> 
> What are you trying to accomplish with this command?

Under normal circumstances, the next thing that would happen after installing cloud-init and our own system, is that packer will create an LXD image which we then use to run our system. The `systemctl restart cloud-init` step in my bug report was intended to just demonstrate what will happen to that image when it boots up in future.

We have tooling around our LXD images that waits for them to be totally "ready" after we launch them, and our definition of "ready" includes `cloud-init status --wait` succeeded. The intention was to prevent race conditions where we start, say, interacting with our LXD containers before cloud-init runs the bootcmd that requests the container's TLS certificate, for example.

We have unit tests for this tooling that reboots a container with a deliberately broken bootcmd, and checks if our tooling reports the error correctly. These tests started hanging forever when the behaviour of `cloud-init status` changed behavior: in the past a broken bootcmd caused `cloud-init status` to terminate with a failure, now it just hangs forever.

> If you were attempting to "run cloud-init", I'd suggest `cloud-init clean --logs --reboot` - or just reboot the system since you are manually installing cloud-init.

We did discover the bug after a reboot. The `systemctl restart` was just an attempt to demonstrate that `cloud-init status` changed behavior with the minimum of extraneous steps in my bug report.

**Comment by pieter-lautus** [comment] 2023-10-17 05:11
To be perfectly clear, here is the sequence of events:

1. Launch images:ubuntu/20.04
2. Install cloud-init into it.
3. Inject `/etc/cloud/cloud.cfg.d/99_broken.cfg` as described above.
4. Take an LXD image of it.
5. Boot up a new container based off this image.
6. Run `cloud-init status --wait` inside this new container, and expect it to fail and report an error. Instead, it hangs forever.

**Comment by pieter-lautus** [comment] 2023-10-17 06:36
The steps our unit tests take are more or less:

```
lxc init images:ubuntu/20.04 foo
lxc start foo
lxc shell foo
apt install cloud-init
vi /etc/cloud/cloud.cfg.d/99_broken.cfg # edit as in first comment
lxc stop foo
lxc copy foo bar
lxc start bar
lxc shell bar
cloud-init status --long --wait
```

The trick is, the above steps don't actually replicate the bug. Our unit test framework uses https://github.com/canonical/pylxd.git to drive LXD using its API, so not all commands are run using the LXD CLI as above. And on top of that the tests run nested in an LXD container.

So I have not been able to isolate the factor that replicates the change in behaviour in `cloud-init status` other than the steps I already gave.

**Comment by holmanb** [comment] 2023-10-18 23:58
> We did discover the bug after a reboot. The systemctl restart was just an attempt to demonstrate that cloud-init status changed behavior with the minimum of extraneous steps in my bug report.

@pieter-lautus I followed your initial bug report, but replaced `systemctl restart cloud-init` with `cloud-init clean --long --reboot` and again with `reboot -h now`. Correct behavior occurred in both cases: `cloud-init status` showed `status: error`, and `cloud-init status --wait` exited immediately).

If you did discover the bug after a reboot, why can't I?

> The trick is, the above steps don't actually replicate the bug.

That sounds reasonable, but I'm not going to try the "more or less unit test" steps because, as you say, they don't reproduce the bug.

> The systemctl restart was just an attempt to demonstrate that cloud-init status changed behavior with the minimum of extraneous steps in my bug report.

If you can share an actual reproducer for your issue, I will be happy to help resolve this issue. That said, if your reproducer is doing something weird like manually running the cloud-init stages, or if it is manually restarting only cloud-init.service (as in your initial report), or doing any other odd restart of cloud-init, then I recommend that you don't do that, because that is not expected (or supported) cloud-init behavior, and `cloud-init status` cannot forsee that you manually ran cloud-init.

I suspect that the answer to "what changed" is that [cloud-init now uses information from systemd](https://github.com/canonical/cloud-init/commit/cf474da7f48572a4aeaea03945b3fd7dbed5e862) to help determine if cloud-init is running, which fixes a bug discovered in `cloud-init status`.

**Comment by holmanb** [comment] 2024-07-23 20:04
can't repro, closing

**Closed by holmanb** 2024-07-23 20:04 UTC
Labels: bug, invalid
