### ISSUE TITLE
runcmd does not run

### ISSUE THREAD

**Issue by risantam89** [canonical/cloud-init#5628] opened 2024-08-19 22:29 UTC
# Bug report
Any commands in runcmd do not run

## Steps to reproduce the problem
```
]# cat /etc/cloud/cloud.cfg
#cloud-config

# The top level settings are used as module
# and base configuration.

# A set of users which may be applied and/or used by various modules
# when a 'default' entry is found it will reference the 'default_user'
# from the distro configuration specified below
users:
  - default

# If this is set, 'root' will not be able to ssh in and they
# will get a message to login instead as the default $user
disable_root: false

cloud_config_modules:
  - runcmd
  

runcmd:
  - [ touch, /root/hi.txt ]
  - [ touch, /run/youbetterwork.txt ]
  - echo hi > /root/hello.txt 
```
Ran:
```
]# cloud-init clean
]# cloud-init init 
```
Results:

```
]# ls /root | grep "h*.txt"
]# 
]# ls /run| grep youbetterwork.txt 
]# 
```

## Environment details
RHEL 8.3 x86_64
Registered to Red Hat and has RHEL 8 Appstream and BaseOS repos enabled only
installed: cloud-init-23.4-7.el8_10.3.noarch

Expecting:

Expect commands in runcmd to execute. In this case touch and echo simple text files. 

Followed the examples as per the link below:
https://cloudinit.readthedocs.io/en/latest/reference/modules.html#runcmd

**Comment by aciba90** [comment] 2024-08-20 10:06
Thanks, @risantam89, for reporting.

IIUC, you are modifying `/etc/cloud/cloud.cfg` to inject the user data on an already running system and manually calling `cloud-init clean && cloud-init init`, right?

That is not the way to interact with cloud-init. 

1. Depending on the platform you are running on, a different [datasource](https://docs.cloud-init.io/en/latest/reference/datasources.html) will be selected, and the way one pass the user-data to cloud-init depends on the datasource.
2. cloud-init is expected to be pre-installed in the image and run at boot time.

Please, refer to one of the [tutorials](https://docs.cloud-init.io/en/latest/tutorial/index.html) and the [docs](https://docs.cloud-init.io/en/latest/tutorial/index.html).

That said, if one insist in running cloud-init manually, then the full cloud-init execution can be reproduced with:

```
cloud-init clean
cloud-init init --local
cloud-init init
cloud-init modules --mode config
cloud-init modules --mode final
```

But this *is not a supported* thing, and those command could change behavior or even disappear.

The reason why `runcmd` did not run is because it typically runs in the config stage, which is executed as part of `cloud-init modules --mode config`.

I am going to close this issue as invalid, please feel free to reopen it if you think it is need.

Thanks!

**Closed by aciba90** 2024-08-20 10:06 UTC
Labels: bug, invalid
