### ISSUE TITLE
Option package_upgrade runs `snap refresh` even if snapd is not installed in the image

### ISSUE THREAD

**Issue by loxK** [canonical/cloud-init#5143] opened 2024-04-04 01:06 UTC
# Bug report
I use images.linuxcontainers.org cloud images. If using the option `package_upgrade`, cloud_init fails because snap isn't installed in these images.

## Steps to reproduce the problem
**test LXD/Incus profile :**

```yaml
config:
  user.vendor-data: |
    #cloud-config
    package_upgrade: true
description: ""
devices: {}
name: test
```

**Script that creates the container :** 
```bash
#!/bin/bash

CONTAINER_NAME="myname"

echo 'Creating container'
incus init images:ubuntu/22.04/cloud $CONTAINER_NAME -p default -p test
echo 'Container created'

echo 'Starting it'
incus start $CONTAINER_NAME

echo 'Waiting for cloud-init to finish up ...'

incus exec $CONTAINER_NAME -- cloud-init status --wait  > /dev/null 2>&1

[ $? -ne 0 ] && echo Cloud-init failed && incus exec $CONTAINER_NAME -- cloud-init status --long && exit 1
echo -n 'Cloud-init finished at '
echo -n `date -R`
```

**The error :** 

```bash
~ ./test.sh
Creating container
Création de myname
Container created
Starting it
Waiting for cloud-init to finish up ...
Cloud-init failed
status: error
extended_status: error
boot_status_code: enabled-by-generator
last_update: Thu, 04 Apr 2024 00:44:15 +0000
detail:
DataSourceNoCloud [seed=/var/lib/cloud/seed/nocloud-net][dsmode=net]
errors:
	- ('package_update_upgrade_install', ProcessExecutionError("Unexpected error while running command.\nCommand: ['snap', 'refresh']\nExit code: -\nReason: [Errno 2] No such file or directory: b'snap'\nStdout: -\nStderr: -"))
recoverable_errors:
WARNING:
	- Package upgrade failed
	- 1 failed with exceptions, re-raising the last one
	- Running module package_update_upgrade_install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py'>) failed
Cloud-init finished at Thu, 04 Apr 2024 11:44:16 +1100
```

**Snap  isn't installed :** 
```bash
root@myname:~ dpkg -l | grep snap
root@myname:~ which snap
root@myname:~ snap
-bash: snap: command not found
```

## Environment details
- Cloud-init version: 23.4.4-0ubuntu0~22.04.1
- Operating System Distribution: Ubuntu
- Cloud provider, platform or installer type: Incus

## cloud-init logs
[cloud-init.tar.gz](https://github.com/canonical/cloud-init/files/14860031/cloud-init.tar.gz)

**Comment by blackboxsw** [comment] 2024-04-04 03:40
Thanks so much @loxK for filing the issues and helping make cloud-init better. This bug is valid against cloud-init 23.4.4 but should also already be fixed per commit cbe5f3a119909d6af51e3f531088c71e54ccc3e6.  This commit is included in upstream release 24.1 which has already been published upstream but is not yet published to Ubuntu 22.04 via the StableReleaseUpdates(SRU) process. We have SRU uploads in the unapproved queued that should publish to jammy within 2 weeks I'd guess https://launchpad.net/ubuntu/jammy/+queue?queue_state=1&queue_text=cloud-init

**Comment by blackboxsw** [comment] 2024-04-04 03:41
We'll close the issue here for upstream as it will be resolved once 24.1 releases. Please feel free to re-open if this problem persists after v. 24.1

**Comment by jbalatero** [comment] 2024-04-26 20:11
The issue persist in my end using `/usr/bin/cloud-init 24.1.3-0ubuntu1~22.04.1`

```
('package_update_upgrade_install', ProcessExecutionError("Unexpected error while running command.\nCommand: ['snap', 'refresh']\nExit code: -\nReason: [Errno 2] No such file or directory: b'snap'\nStdout: -\nStderr: -"))
```

**Comment by blackboxsw** [comment] 2024-04-26 23:58
Seems to work for me given this procedure:
```
cat > 1.yaml <<EOF
#cloud-config
packages: [sl]
EOF
lxc launch ubuntu-daily:jammy j-t -c cloud-init.user-data="$(cat 1.yaml)"
sleep 3
lxc exec j-t  -- cloud-init status --wait --format=yaml
```

**Comment by jbalatero** [comment] 2024-04-27 17:48
it works with your

```
#cloud-config
packages: [sl]
```

but the error persists with

```
#cloud-config
package_upgrade: true
```

**Comment by jbalatero** [comment] 2024-04-27 19:18
hold on, I've recreated the linux machine(I'm using orbstack) and the cloudinit version is now different: `/usr/bin/cloud-init 23.4.4-0ubuntu0~22.04.1`, I'll figure this out first.

**Comment by blackboxsw** [comment] 2024-04-29 03:59
@jbalatero. I see the use-case failed here given your example. This is a different facet of the same type of original issue which looks like we only fixed for package installs, but not package upgrade paths. 

I can reproduce this issue by providing the user-data you referenced on an lxc Ubuntu image where I have removed snapd package, yet provided the following user-data:
```
#cloud-config
package_update: true
```

The former commit cbe5f3a119 fixed this issue for generial package installs, but not the generic package_upgrade/update path.

**Comment by blackboxsw** [comment] 2024-04-29 04:05
I've put up this PR to address this issue. Thanks @jbalatero for the ping here. https://github.com/canonical/cloud-init/pull/5224

**Closed** 2024-04-29 15:07 UTC
Labels: bug

**Comment by blackboxsw** [comment] 2024-04-29 20:06
Upload enqueud for Focal, Jammy, Mantic and Noble per https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2064132
