### ISSUE TITLE
datasource_list no longer allowed in a cloud-init file

### ISSUE THREAD

**Issue by poblahblahblah** [canonical/cloud-init#5240] opened 2024-04-30 19:38 UTC
# Bug report
When cloud-init was upgraded on our Ubuntu 22.04 systems from `23.4.4-0ubuntu0~22.04.1` to  `24.1.3-0ubuntu1~22.04.1` our cloud-init cloud-config file is now considered invalid. I don't see anything in the ChangeLog indicating that a breaking change would be present in the 24.x release branch so I am wondering if this is intentional or a bug.

## Steps to reproduce the problem
Create a #cloud-config file:

```yaml
#cloud-config

package_update: true

datasource_list: ["None"]		# E1
```

Run the schema check: `/usr/bin/cloud-init schema -c /tmp/ud.conf --annotate`

## Environment details
- Cloud-init version: `/usr/bin/cloud-init 24.1.3-0ubuntu1~22.04.1`
- Operating System Distribution: `Ubuntu 22.04`
- Cloud provider, platform or installer type: N/A

## cloud-init logs

```
:~# /usr/bin/cloud-init schema -c /tmp/ud.conf --annotate
#cloud-config

package_update: true

datasource_list: ["None"]		# E1


# Errors: -------------
# E1: Additional properties are not allowed ('datasource_list' was unexpected)


Error: Invalid schema: user-data
```

**Comment by holmanb** [comment] 2024-04-30 20:56
Thanks for reporting this @poblahblahblah. 

> When cloud-init was upgraded on our Ubuntu 22.04 systems from 23.4.4-0ubuntu0~22.04.1 to 24.1.3-0ubuntu1~22.04.1 our cloud-init cloud-config file is now considered invalid. I don't see anything in the ChangeLog indicating that a breaking change would be present in the 24.x release branch so I am wondering if this is intentional or a bug.

Cloud-init has historically ignored invalid configurations, but is now starting to warn about them to help signal to users when they are doing something wrong. I think that this is a case of providing an invalid configuration that was previously ignored. Cloud-init should not be treating datasources any differently than before as a result of this change (if it is doing that, **that** is a breaking change). While this warning log is new on 22.04, it is expected and should help you to understand that the configuration that you provided isn't valid. Since this is has always just been ignored you can probably just delete that line from the configuration.

**Comment by TheRealFalcon** [comment] 2024-04-30 21:07
> you can probably just delete that line from the configuration.

unless your configuration file exists under `/etc/cloud/cloud.cfg.d`. In that case, you still need to keep the `datasource_list` line, but realize that this file is not considered to be cloud-init user data and not intended to be validated with `cloud-init schema`.

The problem is that you're mixing base configuration (the `datasource_list` line) with user data (the rest of the file), but the two get processed independently and should be defined independently. See the [configuration docs](https://cloudinit.readthedocs.io/en/latest/explanation/configuration.html) for more info.

**Comment by poblahblahblah** [comment] 2024-04-30 21:27
> Cloud-init has historically ignored invalid configurations, but is now starting to warn about them to help signal to users when they are doing something wrong. 

This is more than a warning as it caused all of our instances to fail to provision since it throws an error, not a warning which would have been more helpful.

Is the change from silently swallowing warnings on invalid configurations to throwing errors documented anywhere? Seems like something that should have triggered a deprecation warning to give users a heads up that something needs to be corrected. At the very least I would have expected this to be documented as a breaking change.

We will update things on our end.

**Comment by poblahblahblah** [comment] 2024-04-30 21:40
> > you can probably just delete that line from the configuration.
> 
> unless your configuration file exists under `/etc/cloud/cloud.cfg.d`. In that case, you still need to keep the `datasource_list` line, but realize that this file is not considered to be cloud-init user data and not intended to be validated with `cloud-init schema`.
> 
> The problem is that you're mixing base configuration (the `datasource_list` line) with user data (the rest of the file), but the two get processed independently and should be defined independently. See the [configuration docs](https://cloudinit.readthedocs.io/en/latest/explanation/configuration.html) for more info.

This explanation makes a lot of sense @TheRealFalcon, thank you!

**Comment by holmanb** [comment] 2024-04-30 21:42
> This is more than a warning as it caused all of our instances to fail to provision since it throws an error, not a warning which would have been more helpful.

@poblahblahblah What is throwing errors? Cloud-init shouldn't be, we just log a warning.

On 22.04 I see the following:

logs

```python
root@me:~# grep WARN /var/log/cloud-init.log 
2024-04-30 20:43:38,347 - schema.py[WARNING]: Invalid cloud-config provided: Please run 'sudo cloud-init schema --system' to see the schema errors.
2024-04-30 21:34:08,194 - schema.py[WARNING]: Invalid cloud-config provided: Please run 'sudo cloud-init schema --system' to see the schema errors.
```

status output

```
root@me:~# cloud-init status --long
status: done
extended_status: degraded done
boot_status_code: enabled-by-generator
last_update: Tue, 30 Apr 2024 21:34:11 +0000
detail: DataSourceLXD
errors: []
recoverable_errors:
WARNING:
	- Invalid cloud-config provided: Please run 'sudo cloud-init schema --system' to see the schema errors.
```

> Seems like something that should have triggered a deprecation warning to give users a heads up that something needs to be corrected.

This is a warning, which seems to be what you are asking for.

**Comment by poblahblahblah** [comment] 2024-04-30 21:50
@holmanb 

Yes, you are right. Apologies. On our bare metal systems we actually validate the schema on first boot rather than validating when making changes. I am not sure why, but this obviously this is not an issue with cloud-init itself.

**Comment by holmanb** [comment] 2024-04-30 21:58
@poblahblahblah I see, no worries.

It sounds like nothing needs to change with cloud-init at this point, so I'm going to close this issue.

Please feel free to re-open if you believe this to still be an issue.

**Closed by holmanb** 2024-04-30 21:58 UTC
Labels: bug, invalid
