### ISSUE TITLE
Cloud init mounts device to /mnt by default, shadowing other mounts

### ISSUE THREAD

**Issue by SystemParadox** [canonical/cloud-init#4294] opened 2023-07-26 10:47 UTC
# Bug report

- An Azure cloud server was provisioned for us by the customer's IT
- `/etc/fstab` contained an entry to mount `/dev/disk/cloud/azure_resource-part1` on `/mnt`. Changed this to `/mnt/spare` and added some other mounts in subfolders under `/mnt`
- Server was restarted multiple times with no issues
- Server was later reprovisioned with some configuration changes. Cloud-init modified `/etc/fstab` and changed the mount back to `/mnt`, shadowing the other mount points and causing the system to fail.
- Commented out the offending mount entry instead and later had the same issue again

According to https://cloudinit.readthedocs.io/en/latest/reference/modules.html#mounts, cloud-init will attempt to add the following mounts by default:

```
    - ["ephemeral0", "/mnt", "auto","defaults,nofail,x-systemd.requires=cloud-init.service", "0", "2"]
    - ["swap", "none", "swap", "sw", "0", "0"]
```

Mounting devices on `/mnt` by default and shadowing mounts is absolutely not acceptable. Please fix this.

## Steps to reproduce the problem

(see above)

## Environment details

- Cloud-init version: 0.31-2
- Operating System Distribution: Debian 11
- Cloud provider, platform or installer type: Azure

## cloud-init logs

```
2023-07-21 14:57:14,966 - stages.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2023-07-21 14:57:14,968 - cc_mounts.py[DEBUG]: mounts configuration is []
2023-07-21 14:57:14,969 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2023-07-21 14:57:14,969 - cc_mounts.py[DEBUG]: Mapped metadata name ephemeral0 to /dev/disk/cloud/azure_resource
2023-07-21 14:57:14,969 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => /dev/disk/cloud/azure_resource-part1
2023-07-21 14:57:14,969 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2023-07-21 14:57:14,969 - cc_mounts.py[DEBUG]: changed default device swap => None
2023-07-21 14:57:14,969 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2023-07-21 14:57:14,969 - cc_mounts.py[DEBUG]: no need to setup swap
2023-07-21 14:57:14,970 - cc_mounts.py[DEBUG]: Changes to fstab: ['- #/dev/disk/cloud/azure_resource-part1 /mnt auto defaults,nofail,comment=cloudconfig 0 2', '+ /dev/disk/cloud/azure_resource-part1 /mnt auto defaults,nofail,comment=cloudconfig 0 2']
2023-07-21 14:57:16,038 - cc_mounts.py[DEBUG]: Activate mounts: PASS:mount -a
2023-07-21 14:57:16,226 - cc_mounts.py[DEBUG]: Activate mounts: PASS:systemctl daemon-reload
```

**Comment by TheRealFalcon** [comment] 2023-08-01 12:55
This is standard default behavior across all major clouds. We can't change it just to match your preferences.

There are ways to modify or disable this functionality. You can pass user data to remove these mounts. As mentioned in the [documentation](https://cloudinit.readthedocs.io/en/latest/reference/modules.html#mounts), `In order to remove a previously listed mount, an entry can be added to the mounts list containing fs_spec for the device to be removed but no mountpoint (i.e. [ swap ] or [ swap, null ]).`

For you, this means you could pass user data like:
```
#cloud-config
mounts:
 -  ["ephemeral0", null]
```

You could also disable the module entirely if you don't want the default mount functionality when a new instance is booted. To do this, you can remove `- mounts` from `cloud_init_modules:` in `/etc/cloud/cloud.cfg` (or better, override `cloud_init_modules` in `/etc/cloud/cloud.cfg.d`).

Since cloud-init is working as designed, I'm going to close this. Feel free to comment or re-open if I have missed something.

**Closed by TheRealFalcon** 2023-08-01 12:55 UTC
Labels: bug, new

**Comment by SystemParadox** [comment] 2023-08-02 10:29
This isn't just my preference, it's a violation of the linux filesystem hierarchy standard and common expected usage. `/mnt` is not for a single mount point, it's a folder you put mounts in with sensible names.

It's cloud-init that's deciding where to mount it so I'm not sure what you mean by default behaviour across major clouds?

**Comment by TheRealFalcon** [comment] 2023-08-02 16:47
> It's cloud-init that's deciding where to mount it so I'm not sure what you mean by default behaviour across major clouds?

Cloud-init has worked this way for a decade. Any instance launched since then will expect its ephemeral storage to mounted at `/mnt`. An untold number of applications will be relying on that behavior. I'll agree that it isn't an optimal default, and if starting from scratch, I would change it. But at this point we're not going to change that behavior without a **really** good reason, and "it doesn't follow FHS" (like most distros in some way) or "I wasn't expecting that" isn't a good enough reason. There are ways to modify and disable this behavior, so please use those instead.

**Comment by xnox** [comment] 2023-08-03 10:50
> `/mnt` is not for a single mount point, it's a folder you put mounts in with sensible names.

that is incorrect interpretation of FHS, please see FHS 3.0-beta draft that moved all subdir mounts to /media, whilst /mnt is left as is - and commonly used as a single mount point only.

If you want to mount multiple systems you should do them under /media with either well know names i.e. /media/shared-storage. Or even under user specified mounts i.e. /media/xnox/my-usb-drive, which is what used by default by all major linux distributions for over a decade now.

Please switch to /media/<descriptor>/ mount points for your things and stop using /mnt for that.
