### ISSUE TITLE
No local datasource found caused by cloud-init set down and delete eth0

### ISSUE THREAD

**Issue by Jonas-zhang** [canonical/cloud-init#5470] opened 2024-07-01 05:05 UTC
# Bug report
I deploy GCE with Terraform. but cloud-init can't find data from SLES15. I think the root cause is cloud-init set down and delete eth0, so cloud-init can't get metadata from GCP. cloud-init can't connect to GCP metadata, so it think there is no datasource in this instance. After I rerun cloud-init manually, the datasource will be found and everything works well.

## Environment details
- Cloud-init version: 23.3-150100.8.82.3
- Operating System Distribution: SLES15 SP4
- Cloud provider, platform or installer type: Terraform GCP

## cloud-init logs
Partial log in var/log/cloud-init.log.

```
2024-06-28 07:35:00,463 - handlers.py[DEBUG]: start: init-local/search-GCELocal: searching for local data from DataSourceGCELocal
2024-06-28 07:35:00,463 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceGCE.DataSourceGCELocal'>
2024-06-28 07:35:00,464 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2024-06-28 07:35:00,464 - __init__.py[DEBUG]: Machine is configured to run on single datasource DataSourceGCELocal.
2024-06-28 07:35:00,465 - util.py[DEBUG]: Reading from /sys/class/net/eth0/name_assign_type (quiet=False)
2024-06-28 07:35:00,465 - __init__.py[DEBUG]: Found unstable nic names: ['eth0']; calling udevadm settle
2024-06-28 07:35:00,465 - subp.py[DEBUG]: Running command ['udevadm', 'settle'] with allowed return codes [0] (shell=False, capture=True)
2024-06-28 07:35:00,522 - util.py[DEBUG]: Waiting for udev events to settle took 0.057 seconds
2024-06-28 07:35:00,523 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
2024-06-28 07:35:00,523 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
2024-06-28 07:35:00,523 - util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)
2024-06-28 07:35:00,523 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/eth0/device/device
2024-06-28 07:35:00,523 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2024-06-28 07:35:00,523 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2024-06-28 07:35:00,523 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2024-06-28 07:35:00,523 - util.py[DEBUG]: Reading from /sys/class/net/eth0/carrier (quiet=False)
2024-06-28 07:35:00,523 - __init__.py[DEBUG]: Interface has no carrier: eth0
2024-06-28 07:35:00,524 - util.py[DEBUG]: Reading from /sys/class/net/eth0/dormant (quiet=False)
2024-06-28 07:35:00,524 - util.py[DEBUG]: Reading from /sys/class/net/eth0/operstate (quiet=False)
2024-06-28 07:35:00,524 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/eth0/operstate
2024-06-28 07:35:00,524 - DataSourceGCE.py[DEBUG]: Looking for the primary NIC in: ['eth0']
2024-06-28 07:35:00,524 - dhcp.py[DEBUG]: DHCP client selected: dhclient
2024-06-28 07:35:00,524 - dhcp.py[DEBUG]: Performing a dhcp discovery on eth0
2024-06-28 07:35:00,524 - subp.py[DEBUG]: Running command ['ip', 'link', 'set', 'dev', 'eth0', 'up'] with allowed return codes [0] (shell=False, capture=True)
2024-06-28 07:35:00,536 - util.py[DEBUG]: Reading from /sys/class/net/eth0/type (quiet=False)
2024-06-28 07:35:00,536 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/type
2024-06-28 07:35:00,536 - subp.py[DEBUG]: Running command ['/sbin/dhclient', '-1', '-v', '-lf', '/run/dhclient.lease', '-pf', '/run/dhclient.pid', '-sf', '/bin/true', 'eth0'] with allowed return codes [0] (shell=False, capture=True)
2024-06-28 07:35:05,584 - util.py[DEBUG]: All files appeared after 0 seconds: ['/run/dhclient.pid', '/run/dhclient.lease']
2024-06-28 07:35:05,584 - util.py[DEBUG]: Reading from /run/dhclient.pid (quiet=False)
2024-06-28 07:35:05,584 - util.py[DEBUG]: Read 5 bytes from /run/dhclient.pid
2024-06-28 07:35:05,584 - util.py[DEBUG]: Reading from /proc/1796/stat (quiet=True)
2024-06-28 07:35:05,584 - util.py[DEBUG]: Read 300 bytes from /proc/1796/stat
2024-06-28 07:35:05,585 - dhcp.py[DEBUG]: killing dhclient with pid=1796
2024-06-28 07:35:05,586 - util.py[DEBUG]: Reading from /run/dhclient.lease (quiet=False)
2024-06-28 07:35:05,586 - util.py[DEBUG]: Read 807 bytes from /run/dhclient.lease
2024-06-28 07:35:05,586 - ephemeral.py[DEBUG]: Received dhcp lease on eth0 for *****
2024-06-28 07:35:05,586 - ephemeral.py[DEBUG]: Attempting setup of ephemeral network on eth0 with ***** brd *****
2024-06-28 07:35:05,586 - subp.py[DEBUG]: Running command ['ip', '-family', 'inet', 'addr', 'add', '*****', 'broadcast', '*****', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)
2024-06-28 07:35:05,590 - subp.py[DEBUG]: Running command ['ip', '-family', 'inet', 'link', 'set', 'dev', 'eth0', 'up'] with allowed return codes [0] (shell=False, capture=True)
2024-06-28 07:35:05,593 - subp.py[DEBUG]: Running command ['ip', '-4', 'route', 'append', '*****', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)
2024-06-28 07:35:05,595 - subp.py[DEBUG]: Running command ['ip', '-4', 'route', 'append', '0.0.0.0/0', 'via', '*****', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)
2024-06-28 07:35:05,598 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
2024-06-28 07:35:05,603 - util.py[DEBUG]: Resolving URL: http://metadata.google.internal/computeMetadata/v1/ took 0.004 seconds
2024-06-28 07:35:05,603 - DataSourceGCE.py[DEBUG]: http://metadata.google.internal/computeMetadata/v1/ is not resolvable
2024-06-28 07:35:05,603 - util.py[DEBUG]: Crawl of GCE metadata service took 0.005 seconds
2024-06-28 07:35:05,603 - subp.py[DEBUG]: Running command ['ip', '-4', 'route', 'del', '0.0.0.0/0', 'via', '*****', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)
2024-06-28 07:35:05,606 - subp.py[DEBUG]: Running command ['ip', '-4', 'route', 'del', '*****', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)
2024-06-28 07:35:05,608 - subp.py[DEBUG]: Running command ['ip', '-family', 'inet', 'link', 'set', 'dev', 'eth0', 'down'] with allowed return codes [0] (shell=False, capture=True)
2024-06-28 07:35:05,611 - subp.py[DEBUG]: Running command ['ip', '-family', 'inet', 'addr', 'del', '*****', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)
2024-06-28 07:35:05,614 - DataSourceGCE.py[WARNING]: Did not find a fallback interface on gce.
2024-06-28 07:35:05,614 - DataSourceGCE.py[WARNING]: address "http://metadata.google.internal/computeMetadata/v1/" is not resolvable
2024-06-28 07:35:05,614 - __init__.py[DEBUG]: Datasource DataSourceGCELocal not updated for events: boot-new-instance
2024-06-28 07:35:05,614 - handlers.py[DEBUG]: finish: init-local/search-GCELocal: SUCCESS: no local data found from DataSourceGCELocal
2024-06-28 07:35:05,615 - main.py[DEBUG]: No local datasource found
```

**Comment by blackboxsw** [comment] 2024-07-02 20:20
Thank you @Jonas-zhang for filing this bug to make cloud-init better.

Generally speaking the teardown of the ephemeral network configuration during cloud-init's init-local time frame is not what is causing the inability to detect GCE's instance metadata service(IMDS).  What seems to be the problem is the inability of that network configuration to resolve the IMDS seen with this log that you captured.
```
http://metadata.google.internal/computeMetadata/v1/ is not resolvable
```

Something in that initial network config is unable to get ahold of DNS for to resolve the .internal domain for some reason. I'm guessing either an intermittent outage for the network config where this instance is being launched, of some invalid network or DNS configuration in the environment.

Is there an ability to get into the system somehow to troubleshoot these IMDS access issues?
https://cloud.google.com/compute/docs/troubleshooting/troubleshoot-metadata-server


On most instances, we see the following correctly resolving the IMDS

**Comment by blackboxsw** [comment] 2024-07-02 20:23
I'd be curious what the dhcp lease contains `cat '/run/dhclient.lease'` which cloud-init received from Google's DHCP service during launch.

**Comment by Jonas-zhang** [comment] 2024-07-04 09:09
Thanks @blackboxsw for your comments! You are right, there is DNS resolve issue in my environment.  /etc/resolv.conf can't be generated automatic. Which causes http://metadata.google.internal/computeMetadata/v1 can't be resolved. This bug can be closed, thanks again!

**Comment by blackboxsw** [comment] 2024-07-04 12:00
Thanks for the comment @Jonas-zhang!

**Closed by blackboxsw** 2024-07-04 12:00 UTC
Labels: incomplete, bug
