### ISSUE TITLE
[docs]: Users and Groups missing config schema in 'latest' version of docs

### ISSUE THREAD

**Issue by stew3254** [canonical/cloud-init#5625] opened 2024-08-15 20:41 UTC
# Documentation request

In the latest version of the docs (>24.1) the config schema is missing for https://cloudinit.readthedocs.io/en/latest/reference/modules.html#users-and-groups. It tells you to read `/etc/cloud/cloud.cfg`. That might not be possible to do, and even when checking on that file in an Ubuntu 22.04 system it doesn't return a list of all of the keys that are accepted, let alone descriptions of them.

If you switch to something older like 24.1 it still works.

**Comment by aciba90** [comment] 2024-08-16 07:05
Thanks for reporting. Closing as duplicate of https://github.com/canonical/cloud-init/issues/5514.

**Closed by aciba90** 2024-08-16 07:05 UTC
Labels: documentation, new
